// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class Bitacora
    {
        public int? Linea { get; set; }
        public string Mensaje { get; set; }
        public byte? Alta { get; set; }
        public byte? Baja { get; set; }
        public int? Error { get; set; }
        public int FolAuto { get; set; }
        public int? Ref1Int { get; set; }
        public int? Ref2Int { get; set; }
    }
}