// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class BitCuentum
    {
        public int ClaUsuario { get; set; }
        public int ClaSistema { get; set; }
        public DateTime FechaOper { get; set; }
        public int FolBitacora { get; set; }
        public string ClaCuenta { get; set; }
        public int? ClaEmpresa { get; set; }
        public string NomCuenta { get; set; }
        public int? Afectable { get; set; }
        public int? CargoCredito { get; set; }
        public string ClaCuebtaPadre { get; set; }
        public byte? TipoOper { get; set; }
        public string Localizacion { get; set; }
    }
}