// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class BitMovNomina
    {
        public int ClaUsuario { get; set; }
        public int ClaSistema { get; set; }
        public DateTime FechaOper { get; set; }
        public int FolBitacora { get; set; }
        public int ClaTrab { get; set; }
        public int ClaPerded { get; set; }
        public int FolAuto { get; set; }
        public int ClaEmpresa { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int? ClaPuesto { get; set; }
        public int? ClaUbicacion { get; set; }
        public int? ClaDepto { get; set; }
        public int? ClaTurno { get; set; }
        public string TipoMov { get; set; }
        public double? Monto { get; set; }
        public double? MontoTope { get; set; }
        public DateTime? FechaTope { get; set; }
        public double? Acum { get; set; }
        public DateTime? FechaAplica { get; set; }
        public DateTime? FechaMov { get; set; }
        public int? ClaTabSue { get; set; }
        public int? NivTabSue { get; set; }
        public string Referencia { get; set; }
        public byte? TipoOper { get; set; }
        public string Localizacion { get; set; }
    }
}