// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class BitTiempoExt
    {
        public int ClaUsuario { get; set; }
        public int ClaSistema { get; set; }
        public DateTime FechaOper { get; set; }
        public int FolBitacora { get; set; }
        public int ClaTrab { get; set; }
        public DateTime FechaExt { get; set; }
        public int FolAuto { get; set; }
        public int ClaEmpresa { get; set; }
        public int? ClaUbicacion { get; set; }
        public int? ClaDepto { get; set; }
        public int? ClaTurno { get; set; }
        public double? HorasExt { get; set; }
        public string ObsPorque { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int? ClaCausaTe { get; set; }
        public int? ClaTipoTe { get; set; }
        public byte? Status { get; set; }
        public int? ClaTabSue { get; set; }
        public int? NivTabSue { get; set; }
        public byte? TipoOper { get; set; }
        public string Localizacion { get; set; }
    }
}