// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos68854
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190520 { get; set; }
        public string D20190521 { get; set; }
        public string D20190522 { get; set; }
        public string D20190523 { get; set; }
        public string D20190524 { get; set; }
        public string D20190525 { get; set; }
        public string D20190526 { get; set; }
        public string Observacion { get; set; }
    }
}