// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos74810
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190902 { get; set; }
        public string D20190903 { get; set; }
        public string D20190904 { get; set; }
        public string D20190905 { get; set; }
        public string D20190906 { get; set; }
        public string D20190907 { get; set; }
        public string D20190908 { get; set; }
        public string Observacion { get; set; }
    }
}