// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos62343
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190107 { get; set; }
        public string D20190108 { get; set; }
        public string D20190109 { get; set; }
        public string D20190110 { get; set; }
        public string D20190111 { get; set; }
        public string D20190112 { get; set; }
        public string D20190113 { get; set; }
        public string Observacion { get; set; }
    }
}