// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos91798
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20200518 { get; set; }
        public string D20200519 { get; set; }
        public string D20200520 { get; set; }
        public string D20200521 { get; set; }
        public string D20200522 { get; set; }
        public string D20200523 { get; set; }
        public string D20200524 { get; set; }
        public string Observacion { get; set; }
    }
}