// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos105022
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210315 { get; set; }
        public string D20210316 { get; set; }
        public string D20210317 { get; set; }
        public string D20210318 { get; set; }
        public string D20210319 { get; set; }
        public string D20210320 { get; set; }
        public string D20210321 { get; set; }
        public string Observacion { get; set; }
    }
}