// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos65992
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190325 { get; set; }
        public string D20190326 { get; set; }
        public string D20190327 { get; set; }
        public string D20190328 { get; set; }
        public string D20190329 { get; set; }
        public string D20190330 { get; set; }
        public string D20190331 { get; set; }
        public string Observacion { get; set; }
    }
}