// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos67326
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190422 { get; set; }
        public string D20190423 { get; set; }
        public string D20190424 { get; set; }
        public string D20190425 { get; set; }
        public string D20190426 { get; set; }
        public string D20190427 { get; set; }
        public string D20190428 { get; set; }
        public string Observacion { get; set; }
    }
}