// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos97060
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20201005 { get; set; }
        public string D20201006 { get; set; }
        public string D20201007 { get; set; }
        public string D20201008 { get; set; }
        public string D20201009 { get; set; }
        public string D20201010 { get; set; }
        public string D20201011 { get; set; }
        public string Observacion { get; set; }
    }
}