// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos110050
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210523 { get; set; }
        public string D20210524 { get; set; }
        public string D20210525 { get; set; }
        public string D20210526 { get; set; }
        public string D20210527 { get; set; }
        public string D20210528 { get; set; }
        public string D20210529 { get; set; }
        public string Observacion { get; set; }
    }
}