// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos51267
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20180618 { get; set; }
        public string D20180619 { get; set; }
        public string D20180620 { get; set; }
        public string D20180621 { get; set; }
        public string D20180622 { get; set; }
        public string D20180623 { get; set; }
        public string D20180624 { get; set; }
        public string Observacion { get; set; }
    }
}