// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos63359
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190128 { get; set; }
        public string D20190129 { get; set; }
        public string D20190130 { get; set; }
        public string D20190131 { get; set; }
        public string D20190201 { get; set; }
        public string D20190202 { get; set; }
        public string D20190203 { get; set; }
        public string Observacion { get; set; }
    }
}