// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos81712
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20191209 { get; set; }
        public string D20191210 { get; set; }
        public string D20191211 { get; set; }
        public string D20191212 { get; set; }
        public string D20191213 { get; set; }
        public string D20191214 { get; set; }
        public string D20191215 { get; set; }
        public string Observacion { get; set; }
    }
}