// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos51693
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20180625 { get; set; }
        public string D20180626 { get; set; }
        public string D20180627 { get; set; }
        public string D20180628 { get; set; }
        public string D20180629 { get; set; }
        public string D20180630 { get; set; }
        public string D20180701 { get; set; }
        public string Observacion { get; set; }
    }
}