// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos59324
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20181112 { get; set; }
        public string D20181113 { get; set; }
        public string D20181114 { get; set; }
        public string D20181115 { get; set; }
        public string D20181116 { get; set; }
        public string D20181117 { get; set; }
        public string D20181118 { get; set; }
        public string Observacion { get; set; }
    }
}