// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos114564
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210801 { get; set; }
        public string D20210802 { get; set; }
        public string D20210803 { get; set; }
        public string D20210804 { get; set; }
        public string D20210805 { get; set; }
        public string D20210806 { get; set; }
        public string D20210807 { get; set; }
        public string Observacion { get; set; }
    }
}