// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos90297
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20200323 { get; set; }
        public string D20200324 { get; set; }
        public string D20200325 { get; set; }
        public string D20200326 { get; set; }
        public string D20200327 { get; set; }
        public string D20200328 { get; set; }
        public string D20200329 { get; set; }
        public string Observacion { get; set; }
    }
}