// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos110886
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210606 { get; set; }
        public string D20210607 { get; set; }
        public string D20210608 { get; set; }
        public string D20210609 { get; set; }
        public string D20210610 { get; set; }
        public string D20210611 { get; set; }
        public string D20210612 { get; set; }
        public string Observacion { get; set; }
    }
}