// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos95262
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20010101 { get; set; }
        public string D20010102 { get; set; }
        public string D20010103 { get; set; }
        public string D20010104 { get; set; }
        public string D20010105 { get; set; }
        public string D20010106 { get; set; }
        public string D20010107 { get; set; }
        public string Observacion { get; set; }
    }
}