// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos115344
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210815 { get; set; }
        public string D20210816 { get; set; }
        public string D20210817 { get; set; }
        public string D20210818 { get; set; }
        public string D20210819 { get; set; }
        public string D20210820 { get; set; }
        public string D20210821 { get; set; }
        public string Observacion { get; set; }
    }
}