// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos104606
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210308 { get; set; }
        public string D20210309 { get; set; }
        public string D20210310 { get; set; }
        public string D20210311 { get; set; }
        public string D20210312 { get; set; }
        public string D20210313 { get; set; }
        public string D20210314 { get; set; }
        public string Observacion { get; set; }
    }
}