// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos78276
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20191021 { get; set; }
        public string D20191022 { get; set; }
        public string D20191023 { get; set; }
        public string D20191024 { get; set; }
        public string D20191025 { get; set; }
        public string D20191026 { get; set; }
        public string D20191027 { get; set; }
        public string Observacion { get; set; }
    }
}