// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos96178
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20200921 { get; set; }
        public string D20200922 { get; set; }
        public string D20200923 { get; set; }
        public string D20200924 { get; set; }
        public string D20200925 { get; set; }
        public string D20200926 { get; set; }
        public string D20200927 { get; set; }
        public string Observacion { get; set; }
    }
}