// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos62934
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190121 { get; set; }
        public string D20190122 { get; set; }
        public string D20190123 { get; set; }
        public string D20190124 { get; set; }
        public string D20190125 { get; set; }
        public string D20190126 { get; set; }
        public string D20190127 { get; set; }
        public string Observacion { get; set; }
    }
}