// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos55595
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20180903 { get; set; }
        public string D20180904 { get; set; }
        public string D20180905 { get; set; }
        public string D20180906 { get; set; }
        public string D20180907 { get; set; }
        public string D20180908 { get; set; }
        public string D20180909 { get; set; }
        public string Observacion { get; set; }
    }
}