// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos111463
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210613 { get; set; }
        public string D20210614 { get; set; }
        public string D20210615 { get; set; }
        public string D20210616 { get; set; }
        public string D20210617 { get; set; }
        public string D20210618 { get; set; }
        public string D20210619 { get; set; }
        public string Observacion { get; set; }
    }
}