// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos87276
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20200217 { get; set; }
        public string D20200218 { get; set; }
        public string D20200219 { get; set; }
        public string D20200220 { get; set; }
        public string D20200221 { get; set; }
        public string D20200222 { get; set; }
        public string D20200223 { get; set; }
        public string Observacion { get; set; }
    }
}