// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos92352
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20200629 { get; set; }
        public string D20200630 { get; set; }
        public string D20200701 { get; set; }
        public string D20200702 { get; set; }
        public string D20200703 { get; set; }
        public string D20200704 { get; set; }
        public string D20200705 { get; set; }
        public string Observacion { get; set; }
    }
}