// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos103676
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210222 { get; set; }
        public string D20210223 { get; set; }
        public string D20210224 { get; set; }
        public string D20210225 { get; set; }
        public string D20210226 { get; set; }
        public string D20210227 { get; set; }
        public string D20210228 { get; set; }
        public string Observacion { get; set; }
    }
}