// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos48394
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20180430 { get; set; }
        public string D20180501 { get; set; }
        public string D20180502 { get; set; }
        public string D20180503 { get; set; }
        public string D20180504 { get; set; }
        public string D20180505 { get; set; }
        public string D20180506 { get; set; }
        public string Observacion { get; set; }
    }
}