// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos115813
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210822 { get; set; }
        public string D20210823 { get; set; }
        public string D20210824 { get; set; }
        public string D20210825 { get; set; }
        public string D20210826 { get; set; }
        public string D20210827 { get; set; }
        public string D20210828 { get; set; }
        public string Observacion { get; set; }
    }
}