// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos53595
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20180730 { get; set; }
        public string D20180731 { get; set; }
        public string D20180801 { get; set; }
        public string D20180802 { get; set; }
        public string D20180803 { get; set; }
        public string D20180804 { get; set; }
        public string D20180805 { get; set; }
        public string Observacion { get; set; }
    }
}