// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos67009
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190415 { get; set; }
        public string D20190416 { get; set; }
        public string D20190417 { get; set; }
        public string D20190418 { get; set; }
        public string D20190419 { get; set; }
        public string D20190420 { get; set; }
        public string D20190421 { get; set; }
        public string Observacion { get; set; }
    }
}