// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos74025
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190819 { get; set; }
        public string D20190820 { get; set; }
        public string D20190821 { get; set; }
        public string D20190822 { get; set; }
        public string D20190823 { get; set; }
        public string D20190824 { get; set; }
        public string D20190825 { get; set; }
        public string Observacion { get; set; }
    }
}