// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos119686
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20211017 { get; set; }
        public string D20211018 { get; set; }
        public string D20211019 { get; set; }
        public string D20211020 { get; set; }
        public string D20211021 { get; set; }
        public string D20211022 { get; set; }
        public string D20211023 { get; set; }
        public string Observacion { get; set; }
    }
}