// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos58095
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20181022 { get; set; }
        public string D20181023 { get; set; }
        public string D20181024 { get; set; }
        public string D20181025 { get; set; }
        public string D20181026 { get; set; }
        public string D20181027 { get; set; }
        public string D20181028 { get; set; }
        public string Observacion { get; set; }
    }
}