// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos117736
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20210919 { get; set; }
        public string D20210920 { get; set; }
        public string D20210921 { get; set; }
        public string D20210922 { get; set; }
        public string D20210923 { get; set; }
        public string D20210924 { get; set; }
        public string D20210925 { get; set; }
        public string Observacion { get; set; }
    }
}