// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos68160
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190506 { get; set; }
        public string D20190507 { get; set; }
        public string D20190508 { get; set; }
        public string D20190509 { get; set; }
        public string D20190510 { get; set; }
        public string D20190511 { get; set; }
        public string D20190512 { get; set; }
        public string Observacion { get; set; }
    }
}