// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos92555
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20200720 { get; set; }
        public string D20200721 { get; set; }
        public string D20200722 { get; set; }
        public string D20200723 { get; set; }
        public string D20200724 { get; set; }
        public string D20200725 { get; set; }
        public string D20200726 { get; set; }
        public string Observacion { get; set; }
    }
}