// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos76748
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20190930 { get; set; }
        public string D20191001 { get; set; }
        public string D20191002 { get; set; }
        public string D20191003 { get; set; }
        public string D20191004 { get; set; }
        public string D20191005 { get; set; }
        public string D20191006 { get; set; }
        public string Observacion { get; set; }
    }
}