// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos92976
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20200803 { get; set; }
        public string D20200804 { get; set; }
        public string D20200805 { get; set; }
        public string D20200806 { get; set; }
        public string D20200807 { get; set; }
        public string D20200808 { get; set; }
        public string D20200809 { get; set; }
        public string Observacion { get; set; }
    }
}