// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class MovPasoCargaTurnos50715
    {
        public string Trabajador { get; set; }
        public string Nombre { get; set; }
        public string Fechainicio { get; set; }
        public string Fechafin { get; set; }
        public string D20180604 { get; set; }
        public string D20180605 { get; set; }
        public string D20180606 { get; set; }
        public string D20180607 { get; set; }
        public string D20180608 { get; set; }
        public string D20180609 { get; set; }
        public string D20180610 { get; set; }
        public string Observacion { get; set; }
    }
}