// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RelojPoliticaPago
    {
        public int ClaPoliticaPago { get; set; }
        public string NomPoliticaPago { get; set; }
        public int ClaEmpresa { get; set; }
    }
}