// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RelojPerfilTurno
    {
        public int ClaEmpresa { get; set; }
        public int ClaPerfilTurno { get; set; }
        public string NomPerfilTurno { get; set; }
        public string NomCortoPerfilTurno { get; set; }
        public double? HorasProm { get; set; }
        public double? HorasSem { get; set; }
        public double? SepDiaPer { get; set; }
        public double? DiasLabPer { get; set; }
        public string Alfanum1 { get; set; }
        public string Alfanum2 { get; set; }
        public string Alfanum3 { get; set; }
    }
}