// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RetroConceptoFormula
    {
        public int ClaPerded { get; set; }
        public string SqlFormula { get; set; }
    }
}