// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhActOperacion
    {
        public int ClaActividad { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaOperacion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}