// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhAceptaReciboPago
    {
        public int ClaAcepta { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPeriodo { get; set; }
        public int NumNomina { get; set; }
        public int ClaTrab { get; set; }
        public int? ClaUsuario { get; set; }
        public DateTime? FechaAcepta { get; set; }
        public DateTime? FechaConsulta { get; set; }
    }
}