// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhAccionesEvaluacionTrab
    {
        public int FolAuto { get; set; }
        public int ClaEvaluacion { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime Fecha { get; set; }
        public int ClaTrab { get; set; }
        public int ClaAccion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}