// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhAdAdendaNodoAtributo
    {
        public int ClaAtributo { get; set; }
        public int ClaNodo { get; set; }
        public string NomAtributo { get; set; }
        public string ValorAtributo { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}