// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhAfpPeru
    {
        public int FolAuto { get; set; }
        public int ClaEmpresa { get; set; }
        public bool EsAfp { get; set; }
        public int ClaTipo { get; set; }
        public DateTime FechaVig { get; set; }
        public double? Base { get; set; }
        public double? Seguro { get; set; }
        public double? ComisionVariable { get; set; }
        public double? ComisionMixta { get; set; }
        public bool EsMixto { get; set; }
        public DateTime? FechaUltMod { get; set; }
    }
}