// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhAfectaAcum
    {
        public int ClaPerded { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPerdedAfecta { get; set; }
        public int? TipoAfecta { get; set; }
    }
}