// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhAgendum
    {
        public string Nombre { get; set; }
        public int? Fecha { get; set; }
        public string Agenda { get; set; }
    }
}