// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhArticuloCosteo
    {
        public int FolAuto { get; set; }
        public int? ClaAlmacen { get; set; }
        public int? ClaArticulo { get; set; }
        public DateTime FechaHr { get; set; }
        public int? Cantidad { get; set; }
        public double? CostoUnitario { get; set; }
        public double? Valor { get; set; }
        public int? SaldoCantidad { get; set; }
        public double? SaldoValor { get; set; }
        public string Proveedor { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? IdKardex { get; set; }
    }
}