// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhAspectosRevision
    {
        public RhAspectosRevision()
        {
            RhDetAspectosRevisions = new HashSet<RhDetAspectosRevision>();
        }

        public int FolioRevisionAspectos { get; set; }
        public int ClaUbicacion { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomRevision { get; set; }
        public int? Estatus { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? ClaCentroCosto { get; set; }

        public virtual ICollection<RhDetAspectosRevision> RhDetAspectosRevisions { get; set; }
    }
}