// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhBonoPuestoCalif
    {
        public int FolPtoBono { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? ClaPuesto { get; set; }
        public double? RangoIni { get; set; }
        public double? RangoFin { get; set; }
        public double? PctBono { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}