// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhBtActividadExt
    {
        public int FolAuto { get; set; }
        public int? ClaTrab { get; set; }
        public int ClaDato { get; set; }
        public int ClaInstitucion { get; set; }
        public string Otro { get; set; }
        public string Funcion { get; set; }
        public DateTime FechaUltCambio { get; set; }

        public virtual RhBtTrab ClaTrabNavigation { get; set; }
    }
}