// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhBtFamiliar
    {
        public int ClaTrab { get; set; }
        public string NomFamiliar { get; set; }
        public string Parentesco { get; set; }
        public DateTime? FechaNac { get; set; }
        public string LugarNac { get; set; }
        public string Calle { get; set; }
        public string Ciudad { get; set; }
        public int? Cp { get; set; }
        public string Telefono { get; set; }
        public string Empresa { get; set; }
        public string Ocupacion { get; set; }
        public int? Dependiente { get; set; }
        public string Sexo { get; set; }
        public DateTime? FechaMat { get; set; }
        public int? EsBeneSegvida { get; set; }
        public double? PorcBeneSegvida { get; set; }
        public int? EsBeneOtro { get; set; }
        public double? PorcBeneOtro { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaParentesco { get; set; }
        public int? Avisar { get; set; }
        public byte? TieneConstancia { get; set; }
        public DateTime? VigenciaIni { get; set; }
        public DateTime? VigenciaFin { get; set; }
        public byte? EsDiscapacitado { get; set; }
        public byte? EnGuarderia { get; set; }
        public string Guarderia { get; set; }
        public int? NivelEstudios { get; set; }
        public string DescrCapacidadDiferente { get; set; }

        public virtual RhBtTrab ClaTrabNavigation { get; set; }
    }
}