// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhBtTrabRecomiendum
    {
        public int ClaTrab { get; set; }
        public string NombreRecomienda { get; set; }
        public DateTime Fecha { get; set; }
        public string Comentarios { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}