// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCambioFirmasWkf
    {
        public int FolEnvio { get; set; }
        public int? ClaProceso { get; set; }
        public int? IdFlujoProceso { get; set; }
        public int? IdParticipante { get; set; }
        public int? FolSolicitud { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? ClaTrab { get; set; }
        public int? ClaUsuario { get; set; }
        public int? Orden { get; set; }
        public int? EsFinProceso { get; set; }
        public int? EsEditable { get; set; }
        public int? ClaUsuarioMod { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}