// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCalendPerded
    {
        public int FolAuto { get; set; }
        public int? ClaPerded { get; set; }
        public DateTime? FechaPago { get; set; }
        public int? PagoDias { get; set; }
        public double? Pag0Monto { get; set; }
        public DateTime? FIniPer { get; set; }
        public DateTime? FFinPer { get; set; }
        public string Clasif { get; set; }
        public int? ClaPerdedHisto { get; set; }
        public int ClaEmpresa { get; set; }
        public double? PagoMonto { get; set; }
        public int? ClaPerdedNeg { get; set; }
    }
}