// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCapacitacionEmail
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public string CuentaMail { get; set; }
        public byte? ClaFuncion1 { get; set; }
        public byte? ClaFuncion2 { get; set; }
        public byte? ClaFuncion3 { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}