// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCatalogo
    {
        public int ClaDato { get; set; }
        public string NomDato { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? NoVisible { get; set; }
    }
}