// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCatKit
    {
        public RhCatKit()
        {
            RhPuestoKitUniformes = new HashSet<RhPuestoKitUniforme>();
            RhTrabUniformes = new HashSet<RhTrabUniforme>();
        }

        public int ClaKitPrenda { get; set; }
        public string NomKitPrenda { get; set; }
        public double? PrecioKitPrenda { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int ClaEmpresa { get; set; }

        public virtual ICollection<RhPuestoKitUniforme> RhPuestoKitUniformes { get; set; }
        public virtual ICollection<RhTrabUniforme> RhTrabUniformes { get; set; }
    }
}