// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCapacitacionDocto
    {
        public int ClaDocto { get; set; }
        public int ClaCurso { get; set; }
        public string NomDocto { get; set; }
        public int? Tipo { get; set; }
        public DateTime? Fecha { get; set; }
        public byte? Activo { get; set; }
        public byte[] Documento { get; set; }
        public string NomArchivo { get; set; }
    }
}