// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCapFactoresSac
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int IdActividad { get; set; }
        public int IdPeriodoTrab { get; set; }
        public int ClaCurso { get; set; }
        public string DescripcionActividad { get; set; }
        public string LugarActividad { get; set; }
        public DateTime Fecha { get; set; }
        public int Categoria { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public int? ValorActividad { get; set; }
        public double CreditosActividad { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}