// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhcfgPreman
    {
        public int ClaEmpresa { get; set; }
        public int ClaPresupuesto { get; set; }
        public int AnioMes { get; set; }
        public double? DiasMesNat { get; set; }
        public double? DiasMesLab { get; set; }
        public int? ClaRegimenImss { get; set; }
        public int? TablaImpMen { get; set; }
        public int? TablaImpAnu { get; set; }
    }
}