// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhcfgReporte
    {
        public string FrmReporte { get; set; }
        public int ClaSistema { get; set; }
        public string NomReporte { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}