// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCfdiProcesoFin
    {
        public int IdProceso { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaRazonSocial { get; set; }
        public int AnioMes { get; set; }
        public int? ClaFormaPago { get; set; }
        public int? ClaTrab { get; set; }
        public int NumComprobantes { get; set; }
        public int? NumComprobantesFin { get; set; }
        public int? TipoFormato { get; set; }
        public int TipoServicio { get; set; }
        public DateTime FechaServicio { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? EstatusProc { get; set; }
        public int NumSesion { get; set; }
        public int? IdCfdiCanc { get; set; }
        public int? OrigenProceso { get; set; }
    }
}