// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhComportamientoPueVer
    {
        public int ClaVersion { get; set; }
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public int FolioCompetencia { get; set; }
        public int ClaNivel { get; set; }
        public int ClaComportamiento { get; set; }
        public double? Peso { get; set; }
    }
}