// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhConfigDirTrabKsc
    {
        public int FolDir { get; set; }
        public string NomCampo { get; set; }
        public string NomAgrupador { get; set; }
        public int? VisibleKsc { get; set; }
        public int? EsVisibleGrd { get; set; }
        public int? EsInfoBasica { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? ClaPersonalizado { get; set; }
        public string NomEtiqueta { get; set; }
    }
}