// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhConceptosAhorro
    {
        public int ClaEmpresa { get; set; }
        public int ClaPerded { get; set; }
        public int ClaAhorro { get; set; }
        public int Tipo { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}