// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCompetenciaTrab
    {
        public int ClaTrab { get; set; }
        public int FolioCompetencia { get; set; }
        public int ClaEmpresa { get; set; }
        public double? PctCumplimiento { get; set; }
        public string Fortalezas { get; set; }
        public string AreasOportunidad { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}