// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhConceptoPreCap
    {
        public int ClaConcepto { get; set; }
        public int ClaConceptoAfecta { get; set; }
        public byte? TipoAfecta { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}