// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCompromisoEva
    {
        public int ClaEvaluacion { get; set; }
        public int ClaEmpresa { get; set; }
        public int FolAuto { get; set; }
        public double? CalifMin { get; set; }
        public double? CalifMax { get; set; }
        public double? Valor { get; set; }
        public double? Porcentaje { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}