// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhConfrontaErrorEnc
    {
        public string TipoArchivo { get; set; }
        public string Error { get; set; }
        public int ClaUsuario { get; set; }
        public string RegPatronal { get; set; }
        public int? Anio { get; set; }
        public int? Mes { get; set; }
    }
}