// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCompetenciaPueVer
    {
        public int ClaVersion { get; set; }
        public int FolioCompetencia { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPuesto { get; set; }
        public double? Peso { get; set; }
        public double? PctRequerido { get; set; }
        public int ClaNivel { get; set; }
        public byte? AplicaEvaluacion { get; set; }
        public int? NivelMin { get; set; }
        public int? NivelMax { get; set; }
        public double? PesoBusqueda { get; set; }
    }
}