// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhContBanab
    {
        public int? ContFecha { get; set; }
        public int? ClaEmpresa { get; set; }
        public DateTime? Fecha { get; set; }
    }
}