// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCompetenciaPsicoPue
    {
        public int FolioCompetencia { get; set; }
        public int ClaExamen { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPuesto { get; set; }
        public int? NivelMin { get; set; }
        public int? NivelMax { get; set; }
    }
}