// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhComentarioEval
    {
        public int FolComentario { get; set; }
        public int FolPlanDesa { get; set; }
        public DateTime Fecha { get; set; }
        public string Comentario { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}