// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhConfigDescPuesto
    {
        public int ClaEmpresa { get; set; }
        public int ClaSeccion { get; set; }
        public string NomSeccion { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public string ValorStr1 { get; set; }
        public string ValorStr2 { get; set; }
        public string ValorStr3 { get; set; }
        public string ValorStr4 { get; set; }
        public string ValorStr5 { get; set; }
    }
}