// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCompetenciaClasificacion
    {
        public int ClaCompetenciaClasif { get; set; }
        public string NomCompetenciaClasif { get; set; }
    }
}