// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCompetenciaCap
    {
        public int FolioCompetencia { get; set; }
        public int ClaEmpresa { get; set; }
        public int Folio { get; set; }
        public int? MetodoCap { get; set; }
        public string Observaciones { get; set; }
    }
}