// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhConfigDato
    {
        public int ClaValor { get; set; }
        public int ClaDato { get; set; }
        public string ValorDato { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public string ValorCorto { get; set; }
        public double? ValorNum { get; set; }
        public double? ValorNum2 { get; set; }
        public string Descripcion { get; set; }
        public int? NoConfigurable { get; set; }
        public string ValorVarchar1 { get; set; }
        public string ValorVarchar2 { get; set; }
    }
}