// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCtrlActReqpersonal
    {
        public int IdCtrlAct { get; set; }
        public int? FolioReq { get; set; }
        public int? ClaEmpresa { get; set; }
        public string ActividadesRealizadas { get; set; }
    }
}