// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoRecurso
    {
        public int ClaCurso { get; set; }
        public int ClaTipoRecurso { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}