// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoCalendarioTrabPlan
    {
        public int FolioCurso { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int? ConstanciaEntregada { get; set; }
        public int? FolCompromiso { get; set; }
        public int? Eliminado { get; set; }

        public virtual RhCursoCalendarioPlan FolioCursoNavigation { get; set; }
    }
}