// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoSolicitudAltum
    {
        public string Nombre { get; set; }
        public string NombreAlternativo { get; set; }
        public string NombreCorto { get; set; }
        public int? Clasificacion { get; set; }
        public double? Creditos { get; set; }
        public double? HorasPlan { get; set; }
        public double? HorasDia { get; set; }
        public string DescCurso { get; set; }
        public string TipoCurso { get; set; }
        public int? Nacional { get; set; }
        public int? MaxAssist { get; set; }
        public int? MinAssist { get; set; }
        public string Objetivo { get; set; }
        public int ClaSolicitud { get; set; }
        public DateTime? UltRevision { get; set; }
    }
}