// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoTomCand
    {
        public int ClaCand { get; set; }
        public int FolAuto { get; set; }
        public DateTime? FechaCursoTom { get; set; }
        public string NombreCurso { get; set; }
        public double? HorasCurso { get; set; }
        public string EmpresaCurso { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}