// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoPue
    {
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaCurso { get; set; }
        public double? FactorPond { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}