// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoCalAsistente
    {
        public int FolCalendario { get; set; }
        public int ClaTrab { get; set; }
        public byte AsistioSino { get; set; }
        public int ClaEmpresa { get; set; }
        public int FolioCurso { get; set; }

        public virtual RhCursoCalendarioDet Fol { get; set; }
    }
}