// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoCalendarioDetPlan
    {
        public RhCursoCalendarioDetPlan()
        {
            RhCursoCalCostoPlans = new HashSet<RhCursoCalCostoPlan>();
        }

        public int FolCalendario { get; set; }
        public int FolioCurso { get; set; }
        public DateTime FechaIni { get; set; }
        public DateTime FechaFin { get; set; }
        public DateTime? ProgFechaIni { get; set; }
        public DateTime? ProgFechaFin { get; set; }

        public virtual RhCursoCalendarioPlan FolioCursoNavigation { get; set; }
        public virtual ICollection<RhCursoCalCostoPlan> RhCursoCalCostoPlans { get; set; }
    }
}