// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCuestionario
    {
        public int ClaEmpresa { get; set; }
        public int FolCuestionario { get; set; }
        public string NomCuestionario { get; set; }
        public string Observaciones { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaSistema { get; set; }
    }
}