// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhCursoSol
    {
        public int FolAuto { get; set; }
        public int ClaCurso { get; set; }
        public int ClaSupervisor { get; set; }
        public DateTime FechaSolInicio { get; set; }
        public DateTime FechaSolFin { get; set; }
        public byte Estatus { get; set; }
        public int ClaPeriodoDnc { get; set; }
        public int ClaEmpresa { get; set; }
        public byte[] RhJustificacion { get; set; }
        public DateTime? FechaSolicita { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? TipoBusqueda { get; set; }
        public int? TipoDependencia { get; set; }
        public string Comentarios { get; set; }
        public int? IdSesion { get; set; }
    }
}