// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDatosComplementDesha
    {
        public int FolAuto { get; set; }
        public int FolLista { get; set; }
        public int ClaDato { get; set; }
        public int? IdCampo { get; set; }
        public int? TipoCampo { get; set; }
        public string NomCampo { get; set; }
        public int? IdSeccion { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? TipoDatoPer { get; set; }
    }
}