// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDatosTarjetum
    {
        public int ClaTrab { get; set; }
        public DateTime Fecha { get; set; }
        public int ClaEmpresa { get; set; }
        public int? ClaTurno { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int? ClaDepto { get; set; }
        public int? ClaUbicacion { get; set; }
        public int? ClaTabSue { get; set; }
        public int? NivTabSue { get; set; }
    }
}