// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDatoComplementarioValorHistorium
    {
        public DateTime Fecha { get; set; }
        public int ClaControl { get; set; }
        public int ClaEntidad { get; set; }
        public int ClaReferencia1 { get; set; }
        public int ClaReferencia2 { get; set; }
        public int ClaReferencia3 { get; set; }
        public int ClaReferencia4 { get; set; }
        public int ClaReferencia5 { get; set; }
        public string Valor { get; set; }
        public int? ClaUsuario { get; set; }

        public virtual RhDatoComplementario ClaControlNavigation { get; set; }
        public virtual RhEntidad ClaEntidadNavigation { get; set; }
    }
}