// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetLiqNomina
    {
        public string RegPatronal { get; set; }
        public int ClaUsuario { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public string Nss { get; set; }
        public string Rfc { get; set; }
        public string Curp { get; set; }
        public string CreditoInfonavit { get; set; }
        public DateTime? InicioAmortizacion { get; set; }
        public int? NumeroMovs { get; set; }
        public string Nombre { get; set; }
        public double? Sdi { get; set; }
        public int? MesCalculo { get; set; }
        public int? DiasCotizadosMensual { get; set; }
        public int? DiasIncapacidadMensual { get; set; }
        public int? DiasAusentismoMensual { get; set; }
        public double? CuotaFija { get; set; }
        public double? Excedente { get; set; }
        public double? PrestDinero { get; set; }
        public double? GtosMedicos { get; set; }
        public double? RiesgoTrabajo { get; set; }
        public double? InvalidezVida { get; set; }
        public double? Guarderias { get; set; }
        public int? DiasCotizadosBimestral { get; set; }
        public int? DiasIncapacidadBimestral { get; set; }
        public int? DiasAusentismoBimestral { get; set; }
        public double? Retiro { get; set; }
        public double? CesantiaVejez { get; set; }
        public double? AportPatronalInfonavit { get; set; }
        public double? AmortizacionInfonavit { get; set; }

        public virtual RhEncLiqNomina RhEncLiqNomina { get; set; }
    }
}