// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetGpoContable
    {
        public int ClaGpoContable { get; set; }
        public int ClaEmpresa { get; set; }
        public string ClaCuenta { get; set; }
        public double Porcentaje { get; set; }
        public int CargoCredito { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}