// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetEvalCeldum
    {
        public int ClaEvaluacion { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaEquipoEval { get; set; }
        public int ClaFactorEval { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}