// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetEncuestaRelacion
    {
        public int FolAuto { get; set; }
        public int? ClaSistema { get; set; }
        public int? ClaUsuario { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? FolEncuesta { get; set; }
        public int? FolCuestionario { get; set; }
        public int? NumCuestionario { get; set; }
        public int? FolioReq { get; set; }
        public string Observaciones { get; set; }
    }
}