// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetGuiaEntrevistaCompetencium
    {
        public int ClaEmpresa { get; set; }
        public int ClaGuiaEntrevista { get; set; }
        public int FolAuto { get; set; }
        public int FolioCompetencia { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}