// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetDisenioProceso
    {
        public int ClaProceso { get; set; }
        public int ClaDetProceso { get; set; }
        public string NomDetProceso { get; set; }
        public int ClaEmpresa { get; set; }
        public string ClaveObjeto { get; set; }
        public int? ClaObjeto { get; set; }
        public string RutaReporte { get; set; }
        public int? ClaSistema { get; set; }
        public int? Tipo { get; set; }
        public string Folio { get; set; }
        public string Descripcion { get; set; }
        public int? TipoImpresion { get; set; }
        public string Observaciones { get; set; }

        public virtual RhEncDisenioProceso ClaProcesoNavigation { get; set; }
    }
}