// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetEvaluacion
    {
        public int ClaEvaluacion { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaSeccion { get; set; }
        public int? ClaEscala { get; set; }
        public double? PorcRepEval { get; set; }
        public string CapConCalif { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public double? PuntosMinimos { get; set; }
        public byte? NivelCompReq { get; set; }
        public double? PorcCompetEval { get; set; }
    }
}