// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetEncuestaPlan
    {
        public int ClaEmpresa { get; set; }
        public int FolCuestionario { get; set; }
        public int FolEncuesta { get; set; }
        public int FolPlan { get; set; }
        public int FolAuto { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public string Responsable { get; set; }
        public byte? Estatus { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}