// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetNecesidadTrab
    {
        public int ClaEmpresa { get; set; }
        public int ClaNecesidad { get; set; }
        public int ClaTrab { get; set; }
        public int ClaHabilidad { get; set; }
        public int FolAuto { get; set; }
        public DateTime? Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Responsable { get; set; }
        public string Notas { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}