// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetTrabSdoNominal
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaConcepto { get; set; }
        public DateTime FechaMov { get; set; }
        public double? PorcentajeTrab { get; set; }
        public double? MontoTotal { get; set; }

        public virtual RhTrabSdoNominal RhTrabSdoNominal { get; set; }
    }
}