// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetFlujoCondicionGralWkf
    {
        public int IdDetFlujoCondicion { get; set; }
        public int ClaEncFlujoCondicion { get; set; }
        public int ClaProceso { get; set; }
        public int ClaTabla { get; set; }
        public int ClaCampo { get; set; }
        public string Valor { get; set; }
        public int Operador { get; set; }
        public int AplicaSobre { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual RhEncFlujoCondicionGralWkf Cla { get; set; }
    }
}