// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDefTipoPol
    {
        public int ClaTipoPoliza { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPerded { get; set; }
        public string CodigoContable { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public string ContraCuenta { get; set; }
        public byte? PorUbicacion { get; set; }
        public byte? PorDepto { get; set; }
        public byte? PorCentroCosto { get; set; }
        public byte? PorTrabajador { get; set; }
        public int ClaCentroCosto { get; set; }
        public int ClaClasificacion { get; set; }
        public byte? PorPerded { get; set; }
        public string ValorDatoStr1 { get; set; }
        public string ValorDatoStr2 { get; set; }
        public string ValorDatoStr3 { get; set; }
    }
}