// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDestajo
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaOperacion { get; set; }
        public DateTime FechaDestajo { get; set; }
        public double? Unidades { get; set; }
        public double? Horas { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int FolAuto { get; set; }
        public string Des01 { get; set; }
        public string Des02 { get; set; }
        public string Des03 { get; set; }
        public string Des04 { get; set; }
        public string Des05 { get; set; }
        public double? Des06 { get; set; }
        public int? Des07 { get; set; }
        public int? Des08 { get; set; }
        public DateTime? Des09 { get; set; }
        public DateTime? Des10 { get; set; }
    }
}