// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetCursoTrab
    {
        public int FolioCurso { get; set; }
        public int ClaCurso { get; set; }
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int FolAspecto { get; set; }
        public string ClaEscalaEval { get; set; }
        public DateTime FechaEval { get; set; }
    }
}