// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetTipoFiq
    {
        public int ClaTipoFiq { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPerded { get; set; }
        public byte? Orden { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}