// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetEvalTrab
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaEval { get; set; }
        public int ClaEvaluacion { get; set; }
        public int FolioEvaluador { get; set; }
        public int ClaEquipoEval { get; set; }
        public int ClaFactorEval { get; set; }
        public int? ClaTipoEscala { get; set; }
        public string ClaEscalaEval { get; set; }
        public double? PuntosEscala { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}