// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDetInversionAhorro
    {
        public int ClaInversion { get; set; }
        public int ClaAhorro { get; set; }
        public int Numero { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPeriodo { get; set; }
        public int Tipo { get; set; }
        public double Disponible { get; set; }
        public double MontoInversion { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}