// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDesglose
    {
        public int ClaDesglose { get; set; }
        public string NomDesglose { get; set; }
        public double? Moneda1 { get; set; }
        public double? Moneda2 { get; set; }
        public double? Moneda3 { get; set; }
        public double? Moneda4 { get; set; }
        public double? Moneda5 { get; set; }
        public double? Moneda6 { get; set; }
        public double? Moneda7 { get; set; }
        public double? Moneda8 { get; set; }
        public double? Moneda9 { get; set; }
        public double? Moneda10 { get; set; }
        public double? Moneda11 { get; set; }
        public double? Moneda12 { get; set; }
        public double? Moneda13 { get; set; }
        public double? Moneda14 { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}