// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDocumento
    {
        public int ClaEmpresa { get; set; }
        public int ClaDocumento { get; set; }
        public string NomDocumento { get; set; }
        public byte? EsRequisito { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}