// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDocEtapaInvPue
    {
        public int FolEtapaInvPue { get; set; }
        public int FolDocEtapaInvPue { get; set; }
        public string NomDocEtapaInvPue { get; set; }
        public int ClaDocumentoPue { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}