// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDocEntrega
    {
        public int FolEntrega { get; set; }
        public int? FolDoc { get; set; }
        public DateTime? FechaEntrega { get; set; }
        public int? Estatus { get; set; }
        public int? ClaUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}