// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDoctoAviso
    {
        public string ClaDocto { get; set; }
        public int TipoDocto { get; set; }
        public int GrupoAviso { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}