// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhDocsExpPersonal
    {
        public int FolDocExp { get; set; }
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomArchivo { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaDocumento { get; set; }
        public string NomDocumento { get; set; }
        public byte[] Documento { get; set; }
        public string Extension { get; set; }
    }
}