// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEntrevistaCand
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaGuiaEntrevista { get; set; }
        public int FolioReq { get; set; }
        public DateTime? Fecha { get; set; }
        public string NomEntrevistador { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int EmpTrab { get; set; }
    }
}