// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEncFolio
    {
        public int ClaEmpresa { get; set; }
        public int ClaFormaPago { get; set; }
        public string ClaPrefijo { get; set; }
        public int Consecutivo { get; set; }
        public int? ClaOrder { get; set; }
        public DateTime? FechaCaptura { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int ModoFolio { get; set; }
        public int CantConcepto { get; set; }
    }
}