// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEnvioAvisoUsuario
    {
        public int? ClaUsuario { get; set; }
        public int? ClaProceso { get; set; }
        public DateTime? FechaNotificacion { get; set; }
    }
}