// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEncFamiliaPue
    {
        public RhEncFamiliaPue()
        {
            RhDetFamiliaPues = new HashSet<RhDetFamiliaPue>();
        }

        public int FolFamilia { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomFamilia { get; set; }
        public int ClaUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual ICollection<RhDetFamiliaPue> RhDetFamiliaPues { get; set; }
    }
}