// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEncLiquidaAhorro
    {
        public int ClaLiquidacion { get; set; }
        public string NomLiquidacion { get; set; }
        public int Clase { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}