// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEncFlujoCondicionGralWkf
    {
        public RhEncFlujoCondicionGralWkf()
        {
            RhDetFlujoCondicionGralWkfs = new HashSet<RhDetFlujoCondicionGralWkf>();
        }

        public int ClaEncFlujoCondicion { get; set; }
        public int ClaProceso { get; set; }
        public string NomCondicion { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual ICollection<RhDetFlujoCondicionGralWkf> RhDetFlujoCondicionGralWkfs { get; set; }
    }
}