// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEncTabPrestac
    {
        public int ClaTabPre { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomTabPre { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public double? DiasAnio { get; set; }
        public int? TipoDespensa { get; set; }
        public int? TipoTopeDesp { get; set; }
        public string NomImpfijo1 { get; set; }
        public string NomImpfijo2 { get; set; }
        public string NomImpbase1 { get; set; }
        public string NomImpbase2 { get; set; }
        public string NomDiassa1 { get; set; }
        public string NomDiassa2 { get; set; }
        public string NomDiassa3 { get; set; }
        public string NomDiassa4 { get; set; }
        public string NomPorcss { get; set; }
        public int? AplicaTodoPer { get; set; }
        public int? ModificaPresupuestos { get; set; }
        public string Alfanum1 { get; set; }
        public string Alfanum2 { get; set; }
        public string Alfanum3 { get; set; }
        public int? ClaUniNeg { get; set; }

        public virtual RhUniNeg Cla { get; set; }
    }
}