// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEncDisenioProceso
    {
        public RhEncDisenioProceso()
        {
            RhDetDisenioProcesos = new HashSet<RhDetDisenioProceso>();
        }

        public int ClaProceso { get; set; }
        public string NomProceso { get; set; }

        public virtual ICollection<RhDetDisenioProceso> RhDetDisenioProcesos { get; set; }
    }
}