// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEncPolElec
    {
        public int ClaPoliza { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? ClaRazonSocial { get; set; }
        public int? Mes { get; set; }
        public int? Anio { get; set; }
        public string NomPoliza { get; set; }
        public double? VersionE { get; set; }
        public string RfcRazonSocial { get; set; }
        public DateTime? Fecha { get; set; }
        public string ConceptoHaber { get; set; }
        public int? TipoPoliza { get; set; }
        public string Moneda { get; set; }
        public string TipoCambio { get; set; }
        public int? DetallarTrabajador { get; set; }
        public int? Estatus { get; set; }
        public string ConceptoDebe { get; set; }
        public string NumCtaDebe { get; set; }
        public int? ClaBancoOri { get; set; }
        public string TipoSolicitud { get; set; }
        public string NumOrden { get; set; }
        public string NumTramite { get; set; }
        public string Sello { get; set; }
        public string NoCertificado { get; set; }
        public string Certificado { get; set; }
        public string NomCtaDebe { get; set; }
        public string NumCtaEfec { get; set; }
        public string NomCtaEfec { get; set; }
    }
}