// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEquivDet
    {
        public int ClaEmpresa { get; set; }
        public int ClaCat { get; set; }
        public int ClaFort { get; set; }
        public string ClaEqui { get; set; }
        public string DescEqui { get; set; }
    }
}