// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEscolaridadFamiliare
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public DateTime? FechaIni { get; set; }
        public string NomFamiliar { get; set; }
        public int? ClaProfesion { get; set; }
        public string Grado { get; set; }
        public DateTime? FechaFin { get; set; }
        public int? Instituto { get; set; }
        public string Domicilio { get; set; }
        public int? Certificado { get; set; }
        public int? Orden { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaGrado { get; set; }
        public string Horario { get; set; }
        public byte? EsVigente { get; set; }
        public int? AnioEmision { get; set; }
        public string OtraProfesion { get; set; }
        public string OtroInstituto { get; set; }
        public string ObservacionBt { get; set; }
        public double? Calificacion { get; set; }
        public string CtaCorreo { get; set; }
        public int FolAuto { get; set; }
    }
}