// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEvaluacionHab
    {
        public int FolEvaluador { get; set; }
        public int ClaSeccion { get; set; }
        public int ClaHabilidad { get; set; }
        public int ClaEmpresa { get; set; }
        public int FolAuto { get; set; }
        public int ClaEvaluacion { get; set; }
        public DateTime Fecha { get; set; }
        public int ClaTrab { get; set; }
        public int ClaEquipo { get; set; }
        public string ClaEscalaEval { get; set; }
        public double? Calificacion { get; set; }
        public byte? Capacitacion { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public string Observaciones { get; set; }
        public int ClaFase { get; set; }
        public int ClaNivel { get; set; }
        public int ClaComportamiento { get; set; }
        public int ClaPuesto { get; set; }
        public int TipoCompetencia { get; set; }
        public int ClaEscalaInt { get; set; }
    }
}