// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEvdEvaluadore
    {
        public int ClaEmpresa { get; set; }
        public int ClaEvaluador { get; set; }
        public int? ClaTrab { get; set; }
        public string NomTrab { get; set; }
        public int TipoEvaluador { get; set; }
        public string NombreUsuario { get; set; }
        public string PwdEvaluador { get; set; }
        public int? ClaUsuario { get; set; }
        public string CtaCorreo { get; set; }
    }
}