// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEvdTipoDesemp
    {
        public int ClaDesem { get; set; }
        public string NomDesem { get; set; }
        public string NomCorto { get; set; }
    }
}