// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhEvalTrabCalif
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaEval { get; set; }
        public int ClaEvaluacion { get; set; }
        public int FolioEvaluador { get; set; }
        public int ClaGpoFacEval { get; set; }
        public double? PuntosEscala { get; set; }
        public double? EscalaMax { get; set; }
        public int? NumCeldas { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}