// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhExcepFestivo
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public DateTime FechaFestivo { get; set; }
        public DateTime FechaExcepFestivo { get; set; }
    }
}