// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhExamenClinico
    {
        public int ClaExamenCli { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomExamenCli { get; set; }
        public string ObservExamenCli { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? VisibleReq { get; set; }
        public int? TipoEvento { get; set; }
    }
}