// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhExpPersEmail
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaAccion { get; set; }
        public int? Estatus { get; set; }
        public string Email { get; set; }
        public int InfoNomina { get; set; }
    }
}