// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhExcepcionAhorroTrab
    {
        public int ClaEjercicio { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPeriodo { get; set; }
        public int NumNomina { get; set; }
        public int ClaTrab { get; set; }
        public int? TipoAfectacionAhorro { get; set; }
        public int? TipoAfectacionRetiro { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual RhEncEjercicioAhorro ClaEjercicioNavigation { get; set; }
    }
}