// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhExperTrab
    {
        public int ClaEncExper { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaDetExper { get; set; }
        public int ClaTrab { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public double? Duracion { get; set; }
    }
}