// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhExcepcionPagoPrimaAniv
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int Anio { get; set; }
        public string Comentarios { get; set; }
        public int ClaUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}