// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFaltum
    {
        public int ClaFalta { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomFalta { get; set; }
        public string AbrevFalta { get; set; }
        public string TipoFalta { get; set; }
        public int? TipoMovImss { get; set; }
        public byte? AplicaAgui { get; set; }
        public byte? AplicaPtu { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public byte? AplicaProp { get; set; }
        public string NomCorto { get; set; }
        public byte? AplicaImss { get; set; }
        public int? ClaPerded { get; set; }
        public int? GenerarFalta { get; set; }
        public double? HrsFalta { get; set; }
        public int? GeneraCambioTurno { get; set; }
        public byte? AfectaPremio { get; set; }
        public int? SindPermit { get; set; }
        public int? NsindPermit { get; set; }
        public byte? Convertirhrsendias { get; set; }
        public int? ClaPerdedSubmen3 { get; set; }
        public int? ClaPerdedSubmay3 { get; set; }
        public int? NpermAsistperf { get; set; }
        public int? VisibleKiosco { get; set; }
    }
}