// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFactorEval
    {
        public int ClaFactorEval { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaGpoFacEval { get; set; }
        public string NomFactorEval { get; set; }
        public string AlcanceEval { get; set; }
        public int? Orden { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}