// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFamilium
    {
        public RhFamilium()
        {
            RhSubfamilia = new HashSet<RhSubfamilium>();
        }

        public int ClaFamilia { get; set; }
        public string NomFamilia { get; set; }
        public byte TipoArticulo { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual ICollection<RhSubfamilium> RhSubfamilia { get; set; }
    }
}