// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFamiliarCand
    {
        public int ClaCand { get; set; }
        public string NomFamiliar { get; set; }
        public string Calle { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public int? ClaParentesco { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}