// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFamInternoActTmp
    {
        public int ClaTrab { get; set; }
        public string NomFam { get; set; }
        public int FolGrupo { get; set; }
        public int ClaEmpresa { get; set; }
        public int? ClaFam { get; set; }
        public int? EmpFam { get; set; }
        public int? ClaParentesco { get; set; }
        public int? Estatus { get; set; }
        public int? Copiado { get; set; }
    }
}