// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFamiliaresDoctosTmp
    {
        public int FolGrupo { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int ClaFamIntExt { get; set; }
        public string ClaNomFamExt { get; set; }
        public int ClaParentesco { get; set; }
        public string NomDocto { get; set; }
        public byte[] Documento { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}