// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFamInternoCand
    {
        public int ClaCand { get; set; }
        public string NomFam { get; set; }
        public int? ClaParentesco { get; set; }
        public string EmpFam { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}