// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFechaPer
    {
        public int ClaPeriodo { get; set; }
        public int ClaEmpresa { get; set; }
        public int NumNomina { get; set; }
        public int? ClaTabInfo { get; set; }
        public int? ClaRegimenImss { get; set; }
        public int? ClaImssPension { get; set; }
        public int? ClaPropSubsidio { get; set; }
        public int ClaSalarioMinimo { get; set; }
        public int AnioMes { get; set; }
        public DateTime InicioPer { get; set; }
        public DateTime FinPer { get; set; }
        public int? EsSeptimo { get; set; }
        public int? TablaPer { get; set; }
        public int? TablaMen { get; set; }
        public int? TablaAnu { get; set; }
        public int FinMes { get; set; }
        public int? Prorrateo { get; set; }
        public int? MesAcum { get; set; }
        public double? DiasPer { get; set; }
        public double? DiasLab { get; set; }
        public double? SepDia { get; set; }
        public int? AjusteIspt { get; set; }
        public double? DiasIspt { get; set; }
        public int TipoNomina { get; set; }
        public int? DiasPrevCierre { get; set; }
        public int? StatusNomina { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public byte? TipoProp { get; set; }
        public int? CalcSdiFijo { get; set; }
        public int? TipoCalcIspt { get; set; }
        public int? AplicaIspt91 { get; set; }
        public int? AjusteMensual { get; set; }
        public int? AjusteUltNom { get; set; }
        public int? AjusteAnual { get; set; }
        public double? FactorVar1 { get; set; }
        public int? AnioMesVar1 { get; set; }
        public int? AnioMesVar2 { get; set; }
        public byte? CargaArchivo { get; set; }
        public byte? StatusImss { get; set; }
        public DateTime? FechaAjusteIsr { get; set; }
        public byte? CasFinMes { get; set; }
        public byte? NominaCas { get; set; }
        public byte? StatusCierre { get; set; }
        public byte? AjusteMenNetos { get; set; }
        public byte? AjusteAnualEsp { get; set; }
        public byte? CalcIsrAjusteanu { get; set; }
        public byte? ImpMarginalSubsi { get; set; }
        public byte? CalcIsr142risr { get; set; }
        public byte? ProcIsrPrev { get; set; }
        public double? ImpExclusion { get; set; }
        public byte? BandCalcAquienpagar { get; set; }
        public byte? TipoDiasPerNom { get; set; }
        public int? AplicaSepVac { get; set; }
        public int? TipoCalcDiaslab { get; set; }
        public int? TipoCalcPropdias { get; set; }
        public byte? TipoSueIndem { get; set; }
        public byte? TipoDiasPer { get; set; }
        public byte? IncluirBgravDifsue { get; set; }
        public int? Tipofactregresion { get; set; }
        public byte? AplicaSubempArt142 { get; set; }
        public byte? TopeFactorArt142 { get; set; }
        public double? VecesFactorArt142 { get; set; }
        public int? AplicaSubempIndem { get; set; }
        public int? AplicaTotperCompIndem { get; set; }
        public int? AplicaTotperCalcIndem { get; set; }
        public string TipoTrabFiniquito { get; set; }
        public int? Autorizada { get; set; }
        public DateTime? FechaAutoriza { get; set; }
        public DateTime? FechaDesautoriza { get; set; }
        public int? ClaUsuarioAutoriza { get; set; }
        public int? ClaUsuarioCalcula { get; set; }
        public int? ClaUsuarioCierra { get; set; }
        public byte? TopeInggrav117 { get; set; }
        public DateTime? FechaCierre { get; set; }
        public int? IncluyeRecalcPs { get; set; }
        public DateTime? FechaEjercicioIni { get; set; }
        public DateTime? FechaEjercicioFin { get; set; }
        public int FolAuto { get; set; }
        public byte? EstatusSolicitudCierre { get; set; }
        public DateTime? FechaSolicitud { get; set; }
        public int? ClaUsuarioSol { get; set; }
        public DateTime? CfdiFechaPago { get; set; }
    }
}