// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFirmasParam
    {
        public int FolFirma { get; set; }
        public int ClaUsuario { get; set; }
        public int Accion { get; set; }
        public int? ClaTrab { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? SiAcepta { get; set; }
        public int? SiRechaza { get; set; }
        public int? Proceso { get; set; }
        public int? ClaEvaluador { get; set; }
        public int? ClaFormato { get; set; }
        public int? FolEvaluacion { get; set; }
        public int? ClaPuesto { get; set; }
        public int? ClaVersion { get; set; }
        public int? Origen { get; set; }
        public int? ClaTrabEva { get; set; }
        public int? ClaEmpresaEva { get; set; }
        public int? Entero1 { get; set; }
        public int? Entero2 { get; set; }
        public int? Entero3 { get; set; }
        public int? Entero4 { get; set; }
        public int? Entero5 { get; set; }
        public string Cadena1 { get; set; }
        public string Cadena2 { get; set; }
        public string Cadena3 { get; set; }
        public string Cadena4 { get; set; }
        public string Cadena5 { get; set; }
        public DateTime? Fecha1 { get; set; }
        public DateTime? Fecha2 { get; set; }
        public DateTime? Fecha3 { get; set; }
        public DateTime? Fecha4 { get; set; }
        public DateTime? Fecha5 { get; set; }
        public int? ClaEmpresaPue { get; set; }
        public int? Status { get; set; }
        public int ClaProceso { get; set; }
        public int? ClaSistema { get; set; }
        public int? OrdenFirma { get; set; }
        public int? FolPrestamo { get; set; }
        public int? ClaCurso { get; set; }
        public int? ClaUsuarioIni { get; set; }
        public int? TotalFirmas { get; set; }
        public int? FolVacacion { get; set; }
        public int? FolPrimavac { get; set; }
        public int? FolPermiso { get; set; }
        public int? FolCurso { get; set; }
        public int? FolDatosTrab { get; set; }
        public int? BajaLogica { get; set; }
    }
}