// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFiltraCombosComplement
    {
        public int FolAuto { get; set; }
        public int? FolListaOri { get; set; }
        public int? ClaDatoOri { get; set; }
        public int? FolListaFilt { get; set; }
        public int? ClaDatoFilt { get; set; }
        public int? TipoDatoPer { get; set; }
        public int? IdSeccion { get; set; }
        public int? IdCampo { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}