// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFirmasDet
    {
        public int TipoProceso { get; set; }
        public int FolProceso { get; set; }
        public int FolFirma { get; set; }
        public int Agrupador { get; set; }
        public int Orden { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int Estatus { get; set; }
        public int Notificado { get; set; }
    }
}