// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFirmasComentario
    {
        public int TipoProceso { get; set; }
        public int FolProceso { get; set; }
        public int Agrupador { get; set; }
        public int FolFirma { get; set; }
        public int Tipo { get; set; }
        public string Comentario { get; set; }
        public DateTime Fecha { get; set; }
    }
}