// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFlujoAutEtapaInv
    {
        public int FolioReq { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaUsuarioAut { get; set; }
        public int EmpTrab { get; set; }
        public int ClaCandidato { get; set; }
        public int? Estatus { get; set; }
        public int? AutorizaManual { get; set; }
        public int? ClaUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaEtapa { get; set; }
        public int ClaFlujoAut { get; set; }
        public int? TipoEtapa { get; set; }
    }
}