// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhFuenteExternaWeb
    {
        public int FolFuente { get; set; }
        public string ClaEmpresa { get; set; }
        public string ClaPerded { get; set; }
        public string ClaTrab { get; set; }
        public string Monto { get; set; }
        public string MontoTope { get; set; }
        public string FechaTope { get; set; }
        public string Acum { get; set; }
        public string TipoMov { get; set; }
        public string ClaPuesto { get; set; }
        public string ClaUbicacion { get; set; }
        public string ClaCentroCosto { get; set; }
        public string ClaDepto { get; set; }
        public string ClaTurno { get; set; }
        public string ClaTabSue { get; set; }
        public string NivTabSue { get; set; }
        public string Referencia { get; set; }
        public string FechaAplica { get; set; }
        public string FechaMov { get; set; }
        public int? RegValidoSiNo { get; set; }
        public string Comentarios { get; set; }
        public int? Errores { get; set; }
        public int NumSession { get; set; }
        public int ClaUsuario { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}