// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhGeneraLlaveWkf
    {
        public RhGeneraLlaveWkf()
        {
            RhGpoPersonasEnvioWkfs = new HashSet<RhGpoPersonasEnvioWkf>();
        }

        public int FolGpoPersonasEnvio { get; set; }
        public int? IdFlujoProceso { get; set; }

        public virtual ICollection<RhGpoPersonasEnvioWkf> RhGpoPersonasEnvioWkfs { get; set; }
    }
}