// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhGpoCursosProgTrab
    {
        public int FolGpo { get; set; }
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaUltCambio { get; set; }

        public virtual RhGpoProg FolGpoNavigation { get; set; }
    }
}