// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhGraficaxusuario
    {
        public int IdGrafica { get; set; }
        public int ClaUsuario { get; set; }
        public int FolCuestionario { get; set; }
        public int FolMedidaCuestionario { get; set; }
        public int ClaAgrupador { get; set; }
        public string DescGrafica { get; set; }
        public bool Visualiza3d { get; set; }
        public string TipoGrafica { get; set; }
        public string TipoPaleta { get; set; }
    }
}