// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhHabilidad
    {
        public int ClaHabilidad { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomHabilidad { get; set; }
        public int? ClaFactor { get; set; }
        public string Status { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? OriginaDnc { get; set; }
        public int? DetallarEquipo { get; set; }
        public string Descripcion { get; set; }
        public int? FolioCompetencia { get; set; }
        public string NomHabilidadIng { get; set; }
    }
}