// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhHistInfonavit
    {
        public int HistInfId { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public DateTime FechaMov { get; set; }
        public string CredInf { get; set; }
        public int? ValorCreditoInfo { get; set; }
        public double? ValorTasaInfo { get; set; }
        public DateTime? FechaIniDescinf { get; set; }
        public int? TipoMovInfo { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}