// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhHistMovNomina
    {
        public int ClaTrab { get; set; }
        public int ClaPerded { get; set; }
        public int FolAuto { get; set; }
        public int ClaEmpresa { get; set; }
        public int Folio { get; set; }
        public DateTime FechaMov { get; set; }
        public double? Importe { get; set; }
        public string TipoMov { get; set; }
        public double? AcumAnt { get; set; }
        public string Observacion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}