// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhHistPrestamo
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public DateTime FechaPre { get; set; }
        public short Clase { get; set; }
        public DateTime FechaMov { get; set; }
        public int FolAuto { get; set; }
        public int Folio { get; set; }
        public double? Importe { get; set; }
        public int? TipoMov { get; set; }
        public double? SaldoAnt { get; set; }
        public string Observacion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public double? ImporteInteres { get; set; }
        public double? SaldoInteresAnt { get; set; }
    }
}