// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhHistEvaCurso
    {
        public int FolioCurso { get; set; }
        public int ClaCurso { get; set; }
        public int ClaEmpresa { get; set; }
        public int FolEvaCurso { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}