// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhImpCfdiTmpTipoNomina
    {
        public int IdTipoNomina { get; set; }
        public int TipoNomina { get; set; }
        public int? TipoNominaSat { get; set; }
        public byte? Actualiza { get; set; }
        public int Sesion { get; set; }
    }
}