// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhImpCfdiTmpBanco
    {
        public int IdBanco { get; set; }
        public int ClaBanco { get; set; }
        public int? ClaveSat { get; set; }
        public byte? Actualiza { get; set; }
        public int Sesion { get; set; }
    }
}