// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhImpCfdiTmpDetConfigGral
    {
        public int IdConfig { get; set; }
        public int ClaEmpresa { get; set; }
        public string ClaValor { get; set; }
        public int? ValorDatoInt1 { get; set; }
        public int? ValorDatoInt2 { get; set; }
        public string ValorDatoStr1 { get; set; }
        public string ValorDatoStr2 { get; set; }
        public string ValorDatoStr3 { get; set; }
        public byte? Actualiza { get; set; }
        public int Sesion { get; set; }
    }
}