// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhImpCfdiTmpPerdedPue
    {
        public int IdPerdedPue { get; set; }
        public int ClaPerded { get; set; }
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public int? Actualiza { get; set; }
        public int Sesion { get; set; }
    }
}