// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhImpCfdiTmpSubcontratacionTrab
    {
        public int IdSubcontTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public string RfcLabora { get; set; }
        public double PorcentajeTiempo { get; set; }
        public byte? Actualiza { get; set; }
        public int Sesion { get; set; }
    }
}