// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhImpCfdiTmpTipoContrato
    {
        public int IdContrato { get; set; }
        public int ClaContrato { get; set; }
        public int? TipoContratoSat { get; set; }
        public byte? Actualiza { get; set; }
        public int Sesion { get; set; }
    }
}