// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhImpCfdiTmpPerdedPeriodo
    {
        public int IdPerdedPeriodo { get; set; }
        public int ClaPerded { get; set; }
        public int ClaPeriodo { get; set; }
        public int ClaEmpresa { get; set; }
        public int? NumInicial { get; set; }
        public byte? Frecuencia { get; set; }
        public int? Actualiza { get; set; }
        public int Sesion { get; set; }
    }
}