// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhInterinato
    {
        public int FolInterinato { get; set; }
        public int IdDetPosicion { get; set; }
        public int TipoMov { get; set; }
        public DateTime FechaMov { get; set; }
        public DateTime FechaInicial { get; set; }
        public DateTime FechaFinal { get; set; }
        public int ClaEmpresaInterino { get; set; }
        public int ClaTrabInterino { get; set; }
        public int? FolMovHisto { get; set; }
        public string Comentarios { get; set; }
        public int? ClaUsuarioMod { get; set; }
        public int? TipoInterinato { get; set; }

        public virtual RhTrab Cla { get; set; }
        public virtual RhDetPosicionPlantilla IdDetPosicionNavigation { get; set; }
    }
}