// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIndProgramaFuncFecha
    {
        public int ClaProgFecha { get; set; }
        public int ClaProgFunc { get; set; }
        public DateTime? Fecha { get; set; }
        public int? Estatus { get; set; }
        public int? IdSesion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}