// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIndCursoComentario
    {
        public int FolAuto { get; set; }
        public int? FolioCurso { get; set; }
        public int? FolCalendario { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int? Tipo { get; set; }
        public string Comentario { get; set; }
        public int? ClaUsuario { get; set; }
        public int? IdSesion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}