// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIndProgramaParticipan
    {
        public int ClaParticipante { get; set; }
        public int ClaProgFunc { get; set; }
        public int Aplicado { get; set; }
        public string ObservacionesIntruc { get; set; }
        public int? IdSesion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}