// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhInfoProceso
    {
        public RhInfoProceso()
        {
            RhInfoProcesoProgresos = new HashSet<RhInfoProcesoProgreso>();
        }

        public int ClaInfoProceso { get; set; }
        public string NomInfoProceso { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual ICollection<RhInfoProcesoProgreso> RhInfoProcesoProgresos { get; set; }
    }
}