// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIncidenciaTmp
    {
        public int FolIncidencia { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public DateTime Fecha { get; set; }
        public int TipoIncidencia { get; set; }
        public double? Monto { get; set; }
        public int Concepto { get; set; }
        public int Estatus { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}