// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIncidencia
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int Aniomesdia { get; set; }
        public DateTime Fecha { get; set; }
        public int ClaTurno { get; set; }
        public int ClaRoll { get; set; }
        public DateTime? HrEnt { get; set; }
        public DateTime? HrSal { get; set; }
        public double? HrEntTurno { get; set; }
        public double? HrSalTurno { get; set; }
        public int? Asistencia { get; set; }
        public int? MinutosTrab { get; set; }
        public double? HrsTrab { get; set; }
        public int? MinutosCorte { get; set; }
        public double? HrsCorte { get; set; }
        public int? Status { get; set; }
        public int Usuario { get; set; }
        public int TipoReg { get; set; }
    }
}