// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIndPrograma
    {
        public int ClaProg { get; set; }
        public string NomPrograma { get; set; }
        public int FolEvaCurso { get; set; }
        public DateTime? FechaIni { get; set; }
        public DateTime? FechaFin { get; set; }
        public string Comentarios { get; set; }
        public int? EstructuraJerarquica { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? IdSesion { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? ClaPuesto { get; set; }
        public int Estatus { get; set; }
        public int? ClaLugar { get; set; }
        public int ClaUsuarioResp { get; set; }
    }
}