// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIncPre
    {
        public int ClaEmpresa { get; set; }
        public int ClaPresupuesto { get; set; }
        public int Mes { get; set; }
        public double? Incremento { get; set; }
        public int Tipo { get; set; }
        public int Aplicado { get; set; }
        public int? TipoTrab { get; set; }
        public string Filtro { get; set; }
        public int? ClaUbicacion { get; set; }
        public int? ClaArea { get; set; }
        public int? ClaDepto { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int? ClaPuesto { get; set; }
        public int? ClaClasificacion { get; set; }
        public int? TipoCosto { get; set; }
        public int? ClaUbicacionPago { get; set; }
        public int? ClaRazonSocial { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}