// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhIncrementoPre
    {
        public int ClaEmpresa { get; set; }
        public int ClaPresupuesto { get; set; }
        public int ClaConcepto { get; set; }
        public double Incremento { get; set; }
        public byte Tipo { get; set; }
        public byte Aplicado { get; set; }
        public int? Mes { get; set; }
    }
}