// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhInfPeriodoSuperv
    {
        public int FolAuto { get; set; }
        public int ClaPeriodo { get; set; }
        public int ClaSupervisor { get; set; }
        public DateTime? FechaInforme { get; set; }
        public byte? Calificado { get; set; }
    }
}