// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhKardexAlmacen
    {
        public int FolAutoKardex { get; set; }
        public int ClaUnidad { get; set; }
        public int ClaAlmacen { get; set; }
        public int ClaArticulo { get; set; }
        public DateTime FechaHr { get; set; }
        public int Cantidad { get; set; }
        public int Factor { get; set; }
        public int ClaProceso { get; set; }
        public double? ValorCto { get; set; }
        public double? ValorCp { get; set; }
        public double? PrecioVta { get; set; }
        public double? ValorVta { get; set; }
        public double? CostoCapaUnitario { get; set; }
        public int? FolConsulta { get; set; }
        public int? FolEntrega { get; set; }
        public int? IdCapa { get; set; }
        public double? CostoPromUnitario { get; set; }

        public virtual RhProcesosAlmacen ClaProcesoNavigation { get; set; }
        public virtual RhUnidad ClaUnidadNavigation { get; set; }
    }
}