// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhKitPrendum
    {
        public int ClaKitPrenda { get; set; }
        public int ClaPrenda { get; set; }
        public int CantidadPrenda { get; set; }
        public double? PrecioKit { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual RhCatPrendum ClaPrendaNavigation { get; set; }
    }
}