// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhLiquidacionFc
    {
        public int AnioMesInicial { get; set; }
        public int Clase { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public double? TotAporEmp { get; set; }
        public double? TotAporTrab { get; set; }
        public double? TotInteres { get; set; }
        public int? Status { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}