// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhMantenimientoRecipiente
    {
        public int FolMantenimiento { get; set; }
        public int ClaUbicacion { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public int ClaLugar { get; set; }
        public int ClaEquipo { get; set; }
        public int ClaTipo { get; set; }
        public int? ClaProveedor { get; set; }
        public string DescActividad { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}