// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhMovPre
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int ClaConcepto { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public double? Monto { get; set; }
    }
}