// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhMtPlanCarreraParticipa
    {
        public int FolAuto { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int ClaPuesto { get; set; }
        public DateTime? FechaSolicitud { get; set; }
        public DateTime? FechaRespuesta { get; set; }
        public string Comentarios { get; set; }
        public int? Estatus { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}