// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhMtMatrizConfig
    {
        public int ClaEmpresa { get; set; }
        public int ClaRango { get; set; }
        public int ClaEje { get; set; }
        public string NomRango { get; set; }
        public double? ValorMin { get; set; }
        public double? ValorMax { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}