// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhMunicipiosRpu
    {
        public int ClaMunicipioRpu { get; set; }
        public string NomMunicipio { get; set; }
        public string NomMunicipioCorto { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}