// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhNivel
    {
        public int ClaNivel { get; set; }
        public string NomNivel { get; set; }
        public string NomNivelIng { get; set; }
        public string CertNivel { get; set; }
        public byte? MostrarNivel { get; set; }
    }
}