// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhNivelcomportamiento
    {
        public int FolioCompetencia { get; set; }
        public int ClaNivel { get; set; }
        public int ClaComportamiento { get; set; }
        public string NomComportamiento { get; set; }
        public int? TipoComportamiento { get; set; }
    }
}