// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhNoticia
    {
        public int ClaNoticia { get; set; }
        public DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? ClaArea { get; set; }
        public int? ClaDepto { get; set; }
        public int? ClaUbicacionBase { get; set; }
        public int? ClaUbicacionPago { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int? ClaPuesto { get; set; }
        public int? ClaClasificacion { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public int? ClaTipo { get; set; }
        public string Enlace { get; set; }
        public string Titulo { get; set; }
        public int? ClaveAutomatica { get; set; }
        public int Prioridad { get; set; }
        public string Mostrar { get; set; }
    }
}