// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhNotificacionAutomatica
    {
        public int ClaNotificiacion { get; set; }
        public string NomNotificacion { get; set; }
        public string Descripcion { get; set; }
        public int Encendida { get; set; }
        public int DiasFrecuencia { get; set; }
        public string CorreoRemitente { get; set; }
        public int UsuarioAlternativo { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public string Procedimiento { get; set; }
        public string Asunto { get; set; }
        public string Saludo { get; set; }
        public string Cuerpo { get; set; }
        public string Despedida { get; set; }
        public DateTime? FechaUltEjecucion { get; set; }
        public int? ClaUsuarioUltCambio { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}