// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhObjSolParticipante
    {
        public int FolSolObjGpo { get; set; }
        public int FolAuto { get; set; }
        public int ClaParticipante { get; set; }
        public int ClaNivel { get; set; }
        public int FolObjGpoEstruct { get; set; }
        public int Tipo { get; set; }
        public int? Referencia1 { get; set; }
        public int? Referencia2 { get; set; }
        public int? Referencia3 { get; set; }
        public string Referencia4 { get; set; }
        public int Orden { get; set; }
        public int? ClaParticipanteRef { get; set; }
        public int? Estatus { get; set; }
        public int? ClaUsuarioSol { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}