// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhObserv
    {
        public int ClaTrab { get; set; }
        public DateTime FechaObs { get; set; }
        public int Consec { get; set; }
        public int ClaEmpresa { get; set; }
        public string Observ { get; set; }
        public string TipoObs { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? TipoNota { get; set; }
        public string ObservTrab { get; set; }
        public string ObservSup { get; set; }
        public string Motivo { get; set; }
        public string DesMotivo { get; set; }
        public string Lugar { get; set; }
        public int ClaUsuario { get; set; }
        public int? Estatus { get; set; }
        public int FolNota { get; set; }
        public int? EstatusCtrl { get; set; }
    }
}