// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhOpcionDetPrendum
    {
        public int ClaDetPrenda { get; set; }
        public int ClaPrenda { get; set; }
        public int ClaOpcion { get; set; }
        public string NomOpcion { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}