// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhOrgSindical
    {
        public int ClaTrab { get; set; }
        public int ClaOrgsind { get; set; }
        public int ClaEmpresa { get; set; }
        public string PuestoSind { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}