// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhOrdenamientoPantalla
    {
        public int FolAuto { get; set; }
        public int ClaSistema { get; set; }
        public string ClaveObjeto { get; set; }
        public int? ClaPantalla { get; set; }
        public string CampoOrdenar { get; set; }
        public string TipoOrdenamiento { get; set; }
        public int? Orden { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? ClaUsuarioMod { get; set; }
    }
}