// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPlantillaAltum
    {
        public int ClaPlantillaAlta { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomPlantillaAlta { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int? ClaUbicacionBase { get; set; }
        public int? ClaUbicacionPago { get; set; }
        public int? ClaPeriodo { get; set; }
        public int? ClaDepto { get; set; }
        public int? ClaPuesto { get; set; }
        public int? ClaRegImss { get; set; }
        public int? ClaTabPre { get; set; }
        public int? ClaClasificacion { get; set; }
        public int? ClaRoll { get; set; }
        public int? Sind { get; set; }
        public int? ClaTabSue { get; set; }
        public int? NivTabSue { get; set; }
        public int? ClaOperacionProd { get; set; }
        public int? ClaFondoAhorro { get; set; }
        public int? ClaCajaAhorro { get; set; }
        public int? ClaveBusqueda { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaRazonSocial { get; set; }
    }
}