// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPlazoPrestamo
    {
        public int ClaPlazoPrestamo { get; set; }
        public string NomPlazoPrestamo { get; set; }
        public int NumPagosMensuales { get; set; }
        public double? FactPagoSemanal { get; set; }
        public double? FactPagoDecenal { get; set; }
        public double? FactPagoQuincenal { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}