// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPolizaNomina
    {
        public int ClaPeriodo { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTipoPoliza { get; set; }
        public int NumNomina { get; set; }
        public int? ClaGenPol { get; set; }
        public int? NumPoliza { get; set; }
        public int? Status { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}