// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPolElecTranComp
    {
        public int ClaTranDetComp { get; set; }
        public int ClaPoliza { get; set; }
        public string UuidCfdi { get; set; }
        public int? ClaEmpresa { get; set; }
        public int? ClaRazonSocial { get; set; }
        public int? ClaPeriodo { get; set; }
        public int? ClaTrab { get; set; }
        public int? NumNomina { get; set; }
        public double? Monto { get; set; }
        public string Rfc { get; set; }
        public string NumCta { get; set; }
        public string Moneda { get; set; }
        public string TipoCambio { get; set; }
    }
}