// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhProgramaEntAsist
    {
        public int FolAuto { get; set; }
        public int ClaActividad { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int FolActividad { get; set; }
        public DateTime FechaIni { get; set; }
        public DateTime FechaFin { get; set; }
        public byte? Realizado { get; set; }
    }
}