// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhProrrateoExcepcionDepto
    {
        public int ClaEmpresa { get; set; }
        public int ClaRazonSocial { get; set; }
        public int ClaDepto { get; set; }
        public DateTime FechaUltimoCambio { get; set; }
        public int IdSesion { get; set; }
    }
}