// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhProrrateoRazonSocialTmp
    {
        public int IdSesion { get; set; }
        public string ClaEmpresa { get; set; }
        public string ClaTrab { get; set; }
        public string ClaRazonSocial { get; set; }
        public string FechaMov { get; set; }
        public string PctProrrateo { get; set; }
        public string Observaciones { get; set; }
    }
}