// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhProcservPueVer
    {
        public int ClaVersion { get; set; }
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaProceso { get; set; }
        public string NomProceso { get; set; }
        public string NomProcesoAlt { get; set; }
    }
}