// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhProhibeCapturasHisto
    {
        public int FolCapHisto { get; set; }
        public int ClaUsuario { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public int ClaUsuarioAut { get; set; }
        public DateTime? FechaMovto { get; set; }
        public int? TipoMovto { get; set; }
    }
}