// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhProrrateoTrabEmpresa
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int ClaValorProrrateo { get; set; }
        public DateTime FechaMov { get; set; }
        public double PorcentajeProrrateo { get; set; }
        public int EsActual { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int FolioHistLaboral { get; set; }
    }
}