// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhProcservDet
    {
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaProceso { get; set; }
        public int ClaProdserv { get; set; }
        public string NomProdserv { get; set; }
        public string NomProdservAlt { get; set; }
    }
}