// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPuestoPlan
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPuesto { get; set; }
        public byte Tipo { get; set; }
        public int? Orden { get; set; }
        public DateTime? FechaBase { get; set; }
        public int? TiempoEstimado1 { get; set; }
        public int? TiempoEstimado2 { get; set; }
    }
}