// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPuestoReq
    {
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public double? PesoEdad { get; set; }
        public double? PesoSexo { get; set; }
        public double? PesoEdoCivil { get; set; }
        public double? PesoDispViajar { get; set; }
        public double? PesoDispRes { get; set; }
        public double? PesoAutomovil { get; set; }
        public double? PesoExperiencia { get; set; }
        public double? PesoIdioma { get; set; }
        public double? PesoGradoEscolar { get; set; }
        public double? PesoAreaProf { get; set; }
        public double? PesoAreaExp { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public double? PesoCompetencias { get; set; }
        public int? MismoPesoCompetencias { get; set; }
        public double? PesoAreasInteres { get; set; }
        public double? PesoPaqueteCompu { get; set; }
    }
}