// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPuntosRevUbicacion
    {
        public int ClaEmpresa { get; set; }
        public int ClaUbicacion { get; set; }
        public int ClaPuntoRevision { get; set; }
        public int FolioRevision { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int ClaCentroCosto { get; set; }
    }
}