// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPuestoKitUniforme
    {
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaKitPrenda { get; set; }
        public int ClaPerded { get; set; }
        public int TipoMov { get; set; }
        public int PagaTrabajador { get; set; }
        public double? Porcentaje { get; set; }
        public int FolPuestoKitUniforme { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? AplicaStock { get; set; }
        public int? CasoStockUnif { get; set; }

        public virtual RhPerded Cla { get; set; }
        public virtual RhCatKit ClaKitPrendaNavigation { get; set; }
        public virtual RhPuesto ClaNavigation { get; set; }
    }
}