// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhPuestoNivelEstruc
    {
        public int ClaEmpresa { get; set; }
        public int ClaNivelEstrucPto { get; set; }
        public string NomNivelEstrucPto { get; set; }
        public int? ClaUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}