// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRazonSocialProrrateo
    {
        public int ClaEmpresa { get; set; }
        public int ClaRazonSocial { get; set; }
        public int AnioMes { get; set; }
        public double Porcentaje { get; set; }
        public DateTime FechaUltimoCambio { get; set; }
        public int IdSesion { get; set; }
    }
}