// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhReinversionAhorroTmp
    {
        public int IdSesion { get; set; }
        public string ClaInversion { get; set; }
        public int ClaReinversion { get; set; }
        public int ClaAhorro { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}