// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhResDetEva
    {
        public int ClaEvaluacion { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaEval { get; set; }
        public int ClaTrab { get; set; }
        public int ClaSeccion { get; set; }
        public string CompromisoEmp { get; set; }
        public string CompromisoEva { get; set; }
        public double? PuntosEva { get; set; }
        public double? PuntosPond { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}