// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhReqProfesion1Ver
    {
        public int ClaVersion { get; set; }
        public string Grado { get; set; }
        public int ClaPuesto { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaGrado { get; set; }
    }
}