// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRespuestaCuestionario
    {
        public int ClaEmpresa { get; set; }
        public int FolCuestionario { get; set; }
        public int FolPregunta { get; set; }
        public int FolRespuesta { get; set; }
        public string TextoRespuesta { get; set; }
        public double? Puntos { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}