// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRegimenImss
    {
        public int ClaRegimenImss { get; set; }
        public string NomRegimenImss { get; set; }
        public double? EImssCuota { get; set; }
        public double? EImssExcedente { get; set; }
        public double? EImssDinero { get; set; }
        public double? EImssPension { get; set; }
        public double? EImssVida { get; set; }
        public double? EImssRetiro { get; set; }
        public double? EImssCesan { get; set; }
        public double? EImssGuarde { get; set; }
        public double? EInfonavit { get; set; }
        public double? TImssDinero { get; set; }
        public double? TImssExcedente { get; set; }
        public double? TImssPension { get; set; }
        public double? TImssVida { get; set; }
        public double? TImssCesan { get; set; }
        public int? TopeImssEnfmat { get; set; }
        public int? TopeImssRetiro { get; set; }
        public int? TopeImssGuarde { get; set; }
        public int? TopeImssRiesgo { get; set; }
        public int? TopeImssVida { get; set; }
        public int? TopeImssCesan { get; set; }
        public int? TopeImssInfona { get; set; }
        public int? ExcedeEm { get; set; }
        public int? EsModificable { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ModificaPresupuestos { get; set; }
    }
}