// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRelacionExtPue
    {
        public int ClaEmpresa { get; set; }
        public int ClaPuesto { get; set; }
        public int FolAuto { get; set; }
        public string NomRelacionExt { get; set; }
        public string Observaciones { get; set; }
        public int? ClaFrecuencia { get; set; }
        public int? TipoIntercambio { get; set; }
        public string NomRelacionExtIng { get; set; }
        public string ObservacionesIng { get; set; }
    }
}