// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRetroactivoTotal
    {
        public double Importe { get; set; }
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int NumNomina { get; set; }
        public int ClaPeriodo { get; set; }
        public int ClaPerded { get; set; }
        public int ClaCentroCosto { get; set; }
        public int ConceptoRetro { get; set; }
        public int FolioRetroactivo { get; set; }
        public DateTime FechaAplica { get; set; }
    }
}