// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhResEvaEvaluador
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaEvaluacion { get; set; }
        public DateTime FechaEval { get; set; }
        public int FolioEvaluador { get; set; }
        public string NomEvaluador { get; set; }
        public int? TipoEvaluador { get; set; }
        public double? PuntosEval { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClasifEval { get; set; }
    }
}