// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRecursoCap
    {
        public int ClaRecurso { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomRecurso { get; set; }
        public int? TipoRecurso { get; set; }
        public int? Capacidad { get; set; }
        public DateTime? FechaAdquisicion { get; set; }
        public DateTime? FechaMtto { get; set; }
        public double? Costo { get; set; }
        public string Observaciones { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? ClaConceptoAfecta { get; set; }
    }
}