// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRecipientesPresion
    {
        public int FolRecipiente { get; set; }
        public int ClaUbicacion { get; set; }
        public int ClaEquipo { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaLugar { get; set; }
        public string NumSerie { get; set; }
        public string Modelo { get; set; }
        public byte RequiereAuto { get; set; }
        public string Autorizacion { get; set; }
        public string Fabricante { get; set; }
        public int? AnioFabricacion { get; set; }
        public double? Capacidad { get; set; }
        public int? ClaUmCapacidad { get; set; }
        public double? PMax { get; set; }
        public int? ClaUmPMax { get; set; }
        public double? POperacion { get; set; }
        public int? ClaUmPOperacion { get; set; }
        public string Comentarios { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? ClaDepto { get; set; }
        public string Referencia1 { get; set; }
        public string Referencia2 { get; set; }
        public string Referencia3 { get; set; }
    }
}