// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhRiesgoTrabajo
    {
        public int ClaRegImss { get; set; }
        public int ClaEmpresa { get; set; }
        public int Anio { get; set; }
        public double? RiesTrab { get; set; }
        public int? Clase { get; set; }
        public int? Grado { get; set; }
        public int? SDiasSubsidiados { get; set; }
        public double? IPctIncap { get; set; }
        public int? DDefunciones { get; set; }
        public double? NTrabsProm { get; set; }
        public double? FFactorPrima { get; set; }
        public double? MPrimaMin { get; set; }
        public double? RiesTrabAnt { get; set; }
        public string ObsRiesgo { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? TotCasosRt { get; set; }
    }
}