// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSalasCapacitacion
    {
        public int IdSala { get; set; }
        public string NomSala { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}