// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSeccionHab
    {
        public int ClaSeccion { get; set; }
        public int ClaHabilidad { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? FolioCompetencia { get; set; }
    }
}