// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSolCreacionPlaza
    {
        public int FolAuto { get; set; }
        public int FolFirmaReq { get; set; }
        public int FolReq { get; set; }
        public int Estatus { get; set; }
        public string Comentarios { get; set; }
        public int? ClaUsuario { get; set; }
        public int? IdSesion { get; set; }
        public DateTime? FechaSol { get; set; }
        public DateTime? FechaAut { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}