// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSolProrrateoR
    {
        public int FolAuto { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int ClaRazonSocial { get; set; }
        public int? Estatus { get; set; }
        public DateTime FechaMov { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}