// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSolPrestamo
    {
        public int ClaPrestamo { get; set; }
        public int ClaTrab { get; set; }
        public double Importe { get; set; }
        public int TipoPrestamo { get; set; }
        public DateTime FechaPre { get; set; }
        public int Plazo { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int? FolReferencia { get; set; }
        public int? Estatus { get; set; }
        public int? Justificacion { get; set; }
        public string Observaciones { get; set; }
        public int? CancelaPrevio { get; set; }
        public int? ClaPlazoPrestamo { get; set; }

        public virtual RhTipoPrestamo TipoPrestamoNavigation { get; set; }
    }
}