// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSolSegAuto
    {
        public int FolAuto { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public byte Estatus { get; set; }
        public DateTime? FechaSolicita { get; set; }
        public DateTime? FechaAutoriza { get; set; }
        public string Comentarios { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? IdSesion { get; set; }
    }
}