// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSolRepGafete
    {
        public int FolSolRepGafete { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int FolCausaRep { get; set; }
        public string Comentarios { get; set; }
        public DateTime? FechaSolicita { get; set; }
        public DateTime? FechaAutoriza { get; set; }
        public int Estatus { get; set; }
        public int? ClaUsuarioUltCambio { get; set; }

        public virtual RhCausasRepGafete FolCausaRepNavigation { get; set; }
    }
}