// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSubcontratacionPeriodoSat
    {
        public int IdSubcontrataPeriodo { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaPeriodo { get; set; }
        public string RfcLabora { get; set; }
        public double PorcentajeTiempo { get; set; }
        public DateTime FechaUltMod { get; set; }
        public int? UserUltMod { get; set; }
    }
}