// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSubsidioTrab
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int Anio { get; set; }
        public double? ImporteSubsidio { get; set; }
        public byte? TipoCaptura { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}