// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSueldoRecAct
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int FolioNom { get; set; }
        public DateTime? FechaPago { get; set; }
        public int? ClaPeriodo { get; set; }
        public int? NumNomina { get; set; }
        public DateTime? FechaIrreg { get; set; }
        public int? ClaCentroCosto { get; set; }
        public int? ClaDepto { get; set; }
        public int? ClaUbicacionBase { get; set; }
        public double? PDia { get; set; }
        public double? PMes { get; set; }
        public double? PInt { get; set; }
        public double? PRef1 { get; set; }
        public double? PRef2 { get; set; }
        public double? PRef3 { get; set; }
        public double? PRef4 { get; set; }
        public double? PRef5 { get; set; }
        public double? IDia { get; set; }
        public double? IMes { get; set; }
        public double? IInt { get; set; }
        public double? IRef1 { get; set; }
        public double? IRef2 { get; set; }
        public double? IRef3 { get; set; }
        public double? IRef4 { get; set; }
        public double? IRef5 { get; set; }
        public int? ClaFalta { get; set; }
        public string TipoFalta { get; set; }
        public double? HrsFalta { get; set; }
        public int? AClaPuesto { get; set; }
        public double? ADia { get; set; }
        public double? ARef1 { get; set; }
        public double? ARef2 { get; set; }
        public double? ARef3 { get; set; }
        public double? ARef4 { get; set; }
        public double? ARef5 { get; set; }
        public int? ClaTurno { get; set; }
        public double? HorasJor { get; set; }
        public double? BaseEnffija { get; set; }
        public double? BaseEnfexce { get; set; }
        public double? BaseEnfpension { get; set; }
        public double? BaseEnfdinero { get; set; }
        public double? BaseRetiro { get; set; }
        public double? BaseInvalidez { get; set; }
        public double? BaseCesantia { get; set; }
        public double? BaseGuarderia { get; set; }
        public double? BaseRiesgo { get; set; }
        public double? BaseInfonavit { get; set; }
        public double? IeEnffija { get; set; }
        public double? IeEnfexce { get; set; }
        public double? IeEnfdinero { get; set; }
        public double? IeEnfpension { get; set; }
        public double? IeInvalidez { get; set; }
        public double? IeRetiro { get; set; }
        public double? IeCesantia { get; set; }
        public double? IeGuarderia { get; set; }
        public double? IeInfonavit { get; set; }
        public double? IeRiesgo { get; set; }
        public double? ItEnfexce { get; set; }
        public double? ItEnfdinero { get; set; }
        public double? ItEnfpension { get; set; }
        public double? ItInvalidez { get; set; }
        public double? ItCesantia { get; set; }
        public double? IeRetenido { get; set; }
        public double? ItRetenido { get; set; }
        public DateTime? FechaIrregVac { get; set; }
        public int? ClaTabSue { get; set; }
        public int? NivTabSue { get; set; }
        public byte? AplicaSueldo { get; set; }
        public byte? AplicaImss { get; set; }
        public int? TipoRiesgo { get; set; }
        public int? ClaTurnoVac { get; set; }
        public int? ClaTurnoIncap { get; set; }
        public int? ClaTurnoFaltas { get; set; }
        public DateTime? FechaRefVac { get; set; }
        public DateTime? FechaRefIncap { get; set; }
        public DateTime? FechaRefFaltas { get; set; }
        public DateTime? FechaRefPvac { get; set; }
        public DateTime? FechaRefHrsext { get; set; }
        public DateTime? FechaRefPresta { get; set; }
        public DateTime? FechaRefMovnom { get; set; }
        public DateTime? FechaRefDestaj { get; set; }
        public DateTime? FechaRefFestiv { get; set; }
        public double? DiasVac { get; set; }
        public byte? DiaAdicional { get; set; }
        public double? SueldoIntArt33 { get; set; }
        public double? Uma { get; set; }
        public int? FolioDet { get; set; }
        public double? Umi { get; set; }
    }
}