// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSurtidoMedicamento
    {
        public int ClaMedicamento { get; set; }
        public DateTime Fecha { get; set; }
        public int ClaEmpresa { get; set; }
        public string Proveedor { get; set; }
        public int? Cantidad { get; set; }
        public double? Costo { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? Unidades { get; set; }
        public int? Disponible { get; set; }
    }
}