// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhSubfamilium
    {
        public RhSubfamilium()
        {
            RhArticulos = new HashSet<RhArticulo>();
        }

        public int ClaSubfamilia { get; set; }
        public int? ClaFamilia { get; set; }
        public string NomSubfamilia { get; set; }
        public DateTime? FechaUltimoCambio { get; set; }
        public DateTime? FechaUltCambio { get; set; }

        public virtual RhFamilium ClaFamiliaNavigation { get; set; }
        public virtual ICollection<RhArticulo> RhArticulos { get; set; }
    }
}