// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTasaPrestamo
    {
        public int ClaEmpresa { get; set; }
        public DateTime FechaAplica { get; set; }
        public double? TasaA { get; set; }
        public double? TasaB { get; set; }
        public int? ClaUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}