// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTabSue
    {
        public int ClaEmpresa { get; set; }
        public int ClaTabSue { get; set; }
        public string NomTabSue { get; set; }
        public string NomNiv1 { get; set; }
        public string NomNiv2 { get; set; }
        public string NomNiv3 { get; set; }
        public string NomNiv4 { get; set; }
        public string NomNiv5 { get; set; }
        public byte? EsCategoria { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? Orden { get; set; }
        public string NomNiv6 { get; set; }
        public string NomNiv7 { get; set; }
        public string NomNiv8 { get; set; }
        public string NomNiv9 { get; set; }
        public string NomNiv10 { get; set; }
        public string NomNiv11 { get; set; }
        public string NomNiv12 { get; set; }
        public string NomNiv13 { get; set; }
        public string NomNiv14 { get; set; }
        public string NomNiv15 { get; set; }
        public string NomNiv16 { get; set; }
        public string NomNiv17 { get; set; }
        public string NomNiv18 { get; set; }
        public string NomNiv19 { get; set; }
        public string NomNiv20 { get; set; }
        public string NomNiv21 { get; set; }
        public string NomNiv22 { get; set; }
        public string NomNiv23 { get; set; }
        public string NomNiv24 { get; set; }
        public string NomNiv25 { get; set; }
        public string NomNiv26 { get; set; }
        public string NomNiv27 { get; set; }
        public string NomNiv28 { get; set; }
        public string NomNiv29 { get; set; }
        public string NomNiv30 { get; set; }
        public string NomNiv31 { get; set; }
        public string NomNiv32 { get; set; }
        public string NomNiv33 { get; set; }
        public string NomNiv34 { get; set; }
        public string NomNiv35 { get; set; }
        public string NomNiv36 { get; set; }
        public string NomNiv37 { get; set; }
        public string NomNiv38 { get; set; }
        public string NomNiv39 { get; set; }
        public string NomNiv40 { get; set; }
        public string NomNiv41 { get; set; }
        public string NomNiv42 { get; set; }
        public string NomNiv43 { get; set; }
        public string NomNiv44 { get; set; }
        public string NomNiv45 { get; set; }
        public int? TipoTabSue { get; set; }
        public int TipoSueldo { get; set; }
        public string Alfanum1 { get; set; }
        public string Alfanum2 { get; set; }
        public string Alfanum3 { get; set; }
        public int? ClaUniNeg { get; set; }

        public virtual RhUniNeg Cla { get; set; }
    }
}