// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTablaPeso
    {
        public int FolAuto { get; set; }
        public string Sexo { get; set; }
        public double? Talla { get; set; }
        public double? LimInf { get; set; }
        public double? LimInfRecom { get; set; }
        public double? LimSup { get; set; }
        public double? LimSupRecom { get; set; }
        public double? PesoPromedio { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}