// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTempVacacion
    {
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int Antig { get; set; }
        public int FolAuto { get; set; }
        public double? DiasVac { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public double? DiasPagoVac { get; set; }
        public DateTime? FechaPagoVac { get; set; }
        public double? DiasPriVac { get; set; }
        public DateTime? FechaPagoPri { get; set; }
        public int FolioVac { get; set; }
        public int? Autorizar { get; set; }
        public double? DiasVacLab { get; set; }
        public DateTime? FechaIniVaclab { get; set; }
        public DateTime? FechaFinVaclab { get; set; }
        public double? VacTabPrestac { get; set; }
        public double? PriTabPrestac { get; set; }
        public int Anio { get; set; }
        public double? DiasVacNat { get; set; }
        public int? Agrupador { get; set; }
        public int? MsjVal { get; set; }
        public string MsjTxt { get; set; }
    }
}