// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTemasCursoDet
    {
        public int FolAuto { get; set; }
        public int ClaTema { get; set; }
        public string NomTema { get; set; }

        public virtual RhTemasCurso FolAutoNavigation { get; set; }
    }
}