// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTipoMov
    {
        public int ClaTipoMov { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomTipoMov { get; set; }
        public int? TipoMovImss { get; set; }
        public int? TipoBajaImss { get; set; }
        public int? CausaRotacion { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public string NomCorto { get; set; }
        public int? TipoRotacion { get; set; }
        public int TipoBajaFiniquito { get; set; }
        public int? TipoMovIssste { get; set; }
        public int? AplicaCambioPlaza { get; set; }
        public int? NoAfectaPlantilla { get; set; }
        public int? AplicaPersonal { get; set; }
    }
}