// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTipoConceptoAhorro
    {
        public int ClaTipo { get; set; }
        public string NomTipoConcepto { get; set; }
        public int Cargo { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}