// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTipoMovRep
    {
        public int ClaTipoMov { get; set; }
        public int ClaEmpresa { get; set; }
        public string ComandoRep { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}