// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTiempoCalcNomina
    {
        public int ClaEmpresa { get; set; }
        public int ClaPeriodo { get; set; }
        public int NumNomina { get; set; }
        public string Proceso { get; set; }
        public int ClaPerded { get; set; }
        public DateTime Inicio { get; set; }
        public DateTime Fin { get; set; }
        public int FolioNom { get; set; }
    }
}