// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTipoPrestamoJust
    {
        public int FolAuto { get; set; }
        public int TipoPrestamo { get; set; }
        public int ClaJustificacion { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}