// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTrabSdoNominal
    {
        public RhTrabSdoNominal()
        {
            RhDetTrabSdoNominals = new HashSet<RhDetTrabSdoNominal>();
        }

        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public DateTime FechaMov { get; set; }
        public double? SdoAdministrativo { get; set; }
        public double? SdoNominal { get; set; }

        public virtual ICollection<RhDetTrabSdoNominal> RhDetTrabSdoNominals { get; set; }
    }
}