// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTrabGastosTmp
    {
        public int ClaEmpresa { get; set; }
        public int ClaTrab { get; set; }
        public int ClaGasto { get; set; }
        public int FolGrupo { get; set; }
        public int Estatus { get; set; }
        public double? Monto { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? Copiado { get; set; }
    }
}