// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhTraspasosAhorro
    {
        public DateTime FechaMov { get; set; }
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaAhorroOrigen { get; set; }
        public decimal AhorroEmp { get; set; }
        public int ClaAhorroDestino { get; set; }
        public decimal AhorroTrab { get; set; }
        public decimal Rendimientos { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}