// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhUdi
    {
        public DateTime FechaUdi { get; set; }
        public double MontoUdi { get; set; }
        public int ClaUsuario { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}