// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhUma
    {
        public int ClaUma { get; set; }
        public string NomUma { get; set; }
        public double Uma { get; set; }
        public DateTime FechaIni { get; set; }
        public byte ModificaPresupuestos { get; set; }
        public DateTime FechaUltCambio { get; set; }
        public int ClaUsuarioUltCambio { get; set; }
    }
}