// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhVarUsuario
    {
        public string ClaVar { get; set; }
        public string LlaveRefer { get; set; }
        public int FolAuto { get; set; }
        public int? ClaEmpresa { get; set; }
        public double? ValorVarUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}