// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhVacuna
    {
        public int ClaEmpresa { get; set; }
        public int ClaVacuna { get; set; }
        public string NomVacuna { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public int? TipoVacuna { get; set; }
    }
}