// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RhVerificacionCondicionesDet
    {
        public int FolCondicion { get; set; }
        public int FolVerific { get; set; }
        public string Condiciones { get; set; }
        public string CausaEfecto { get; set; }
        public string Incumplimiento { get; set; }
        public string Recomendacion { get; set; }
        public DateTime? FechaCumplimiento { get; set; }
        public string Observaciones { get; set; }
        public DateTime FechaUltCambio { get; set; }
    }
}