// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class RptProceso
    {
        public string NomProceso { get; set; }
        public string DescProceso { get; set; }
        public string NomSubproceso { get; set; }
        public string DescSubproceso { get; set; }
        public string NomLogEntidadBase { get; set; }
        public string NomFisEntidadBase { get; set; }
        public string NomLogEntidades { get; set; }
    }
}