// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SenTablaPeriUb
    {
        public int? ClaUbiFortia { get; set; }
        public string ClaUbiSen { get; set; }
        public int? ClaPeriodoFortia { get; set; }
        public string ClaPeriodoSen { get; set; }
        public string ClaseSen { get; set; }
        public DateTime? FechaUltCambio { get; set; }
    }
}