// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysAplicacionExterna
    {
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string NomAplicacion { get; set; }
    }
}