// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysBitacoraProceso
    {
        public DateTime FechaBitacora { get; set; }
        public int ClaUsuario { get; set; }
        public string Proceso { get; set; }
        public string Operacion { get; set; }
        public string IpAdress { get; set; }
        public int? ClaSistema { get; set; }
        public string ClaveObjeto { get; set; }
        public string Comentarios { get; set; }
        public int FolProceso { get; set; }
    }
}