// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysConfigRegion
    {
        public int ClaRegion { get; set; }
        public int ClaEmpresa { get; set; }
        public string NomRegion { get; set; }
        public bool Activa { get; set; }
    }
}