// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysPreguntasSeg
    {
        public SysPreguntasSeg()
        {
            RhPreguntasSegUsuarios = new HashSet<RhPreguntasSegUsuario>();
        }

        public int ClaPregunta { get; set; }
        public string NomPregunta { get; set; }
        public DateTime FechaUltCambio { get; set; }

        public virtual ICollection<RhPreguntasSegUsuario> RhPreguntasSegUsuarios { get; set; }
    }
}