// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysSegObjetoSistema
    {
        public int ClaSistema { get; set; }
        public int ClaObjeto { get; set; }
    }
}