// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysSegGpoUsuarioObjeto
    {
        public int ClaSistema { get; set; }
        public int ClaGpoUsuario { get; set; }
        public int ClaModulo { get; set; }
        public int ClaObjeto { get; set; }
        public short? TipoAccion { get; set; }

        public virtual SysSegModulo Cla { get; set; }
        public virtual SysGpoUsuario ClaGpoUsuarioNavigation { get; set; }
        public virtual SysSegObjeto ClaNavigation { get; set; }
        public virtual SysSistema ClaSistemaNavigation { get; set; }
    }
}