// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysSegBitacora
    {
        public int FolAuto { get; set; }
        public DateTime? FechaOper { get; set; }
        public int? ClaUsuario { get; set; }
        public int? ClaObjeto { get; set; }
        public int? ClaSistema { get; set; }
        public int? TipoOper { get; set; }
        public string Sref1 { get; set; }
    }
}