// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysSegTrabHisto
    {
        public int IdHistoSegTrab { get; set; }
        public int ClaTrab { get; set; }
        public int ClaEmpresa { get; set; }
        public int ClaUsuario { get; set; }
        public DateTime? FechaUltCambio { get; set; }
        public DateTime FechaModificacion { get; set; }
        public int PersonaModifica { get; set; }
        public byte BajaSino { get; set; }
        public DateTime? FechaBaja { get; set; }
        public int? PersonaBaja { get; set; }
    }
}