// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysSegConfObjeto
    {
        public int ClaObjeto { get; set; }
        public int? Orden { get; set; }
        public int? OrdenAgrupador { get; set; }
    }
}