// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysSistemaBack
    {
        public int ClaSistema { get; set; }
        public string NomSistema { get; set; }
        public string NomCortoSis { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public byte? Visible { get; set; }
        public string NomPers { get; set; }
        public string UrlV5 { get; set; }
    }
}