// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class SysVersionEnc
    {
        public string Version { get; set; }
        public string Observacion { get; set; }
        public DateTime? Fecha { get; set; }
        public string KeyProd { get; set; }
        public byte[] IdJobIncrSdoGradual { get; set; }
    }
}