// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.fortia.Entities
{
    public partial class TemporalCdebmo
    {
        public string EbimCveUnit { get; set; }
        public string EbimNumAfil { get; set; }
        public int? EbimOrigMov { get; set; }
        public int? EbimTipoMov { get; set; }
        public DateTime? EbimFechaMov { get; set; }
        public int? EbimDiasCobro { get; set; }
        public double? EbimSalBase { get; set; }
        public double? EbimImpRetiro { get; set; }
        public double? EbimImpCyv { get; set; }
        public double? EbimSalBasInf { get; set; }
        public double? EbimImpInf { get; set; }
        public double? EbimImpAmor { get; set; }
        public int? Anio { get; set; }
        public int? Mes { get; set; }
        public int? ClaUsuario { get; set; }
    }
}