// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace biz.rebel_wings.Entities
{
    public partial class CatSection
    {
        public CatSection()
        {
            Permissions = new HashSet<Permission>();
        }

        public int Id { get; set; }
        public int? SubMenuId { get; set; }
        public string? Name { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatSubMenu? SubMenu { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}