// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Aenadto
    {
        public int Codigo { get; set; }
        public double? Dto { get; set; }
    }
}