// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Albventatarjeta
    {
        public string Numserie { get; set; }
        public int Numalbaran { get; set; }
        public string N { get; set; }
        public int Idtarjeta { get; set; }
        public double? Saldo { get; set; }

        public virtual Albventacab NNavigation { get; set; }
    }
}