// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Articuloscomentariosweb
    {
        public int Idhotel { get; set; }
        public int Codarticulo { get; set; }
        public int Codidioma { get; set; }
        public string Descripcion { get; set; }
        public string Comentario { get; set; }

        public virtual Articulo1 CodarticuloNavigation { get; set; }
    }
}