// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Cajasasignada
    {
        public int Idterminal { get; set; }
        public int Codvendedor { get; set; }
        public string Caja { get; set; }

        public virtual Terminale IdterminalNavigation { get; set; }
    }
}