// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Camposlibresposible
    {
        public short Tabla { get; set; }
        public string Campo { get; set; }
        public short Posicion { get; set; }
        public string Valor { get; set; }

        public virtual Camposlibresconfig Camposlibresconfig { get; set; }
    }
}