// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Cotizacione
    {
        public DateTime Fecha { get; set; }
        public int Codmoneda { get; set; }
        public double Cotizacion { get; set; }
        public byte[] Version { get; set; }

        public virtual Moneda CodmonedaNavigation { get; set; }
    }
}