// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Embalaje
    {
        public string Codembalaje { get; set; }
        public string Descripcion { get; set; }
        public double? Longitud { get; set; }
        public double? Altura { get; set; }
        public double? Anchura { get; set; }
    }
}