// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Facturasventaret
    {
        public string Numserie { get; set; }
        public int Numfactura { get; set; }
        public string N { get; set; }
        public int Numlin { get; set; }
        public double? Base { get; set; }
        public double? Porcret { get; set; }
        public double? Importe { get; set; }
        public int? Tiporet { get; set; }
        public int? Regimret { get; set; }

        public virtual Facturasventum NNavigation { get; set; }
    }
}