// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Facturasventacamposlibre
    {
        public string Numserie { get; set; }
        public int Numfactura { get; set; }
        public string N { get; set; }
        public string Requisicion { get; set; }
        public string Usocfdi { get; set; }
        public string Metodopago { get; set; }
        public string Formapago { get; set; }
        public string Factura { get; set; }
        public string Tiporelacion { get; set; }

        public virtual Facturasventum NNavigation { get; set; }
    }
}