// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Favoritostiposterminal
    {
        public int Idtipoterminal { get; set; }
        public int Posicion { get; set; }
        public int? Codfavorito { get; set; }

        public virtual Tiposterminal IdtipoterminalNavigation { get; set; }
    }
}