// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Formaspagocajaraiz
    {
        public string Codformapago { get; set; }
        public string Caja { get; set; }
        public string Raizcobro { get; set; }
    }
}