// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Formatosarticulo
    {
        public int Codarticulo { get; set; }
        public int Codformato { get; set; }
        public string Codbarras { get; set; }
        public string Compra { get; set; }
        public string Venta { get; set; }
        public string Visibleenventa { get; set; }
        public string Visibleencompra { get; set; }
    }
}