// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Hcierrehabitacione
    {
        public int Idhotel { get; set; }
        public short Planta { get; set; }
        public int Habitacion { get; set; }
        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }
        public string Motivo { get; set; }
        public int? Codempleado { get; set; }
        public int? Idbloqueo { get; set; }
        public DateTime? Hora { get; set; }
    }
}