// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Hcuposcomentario
    {
        public int Idcupo { get; set; }
        public int Numcomentario { get; set; }
        public int? Codidioma { get; set; }
        public string Comentario { get; set; }

        public virtual Hcupo IdcupoNavigation { get; set; }
    }
}