// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Hcuposestadosdefecto
    {
        public int Idcupo { get; set; }
        public int Codigo { get; set; }
        public string Idestado { get; set; }
        public bool? Poner { get; set; }

        public virtual Hcupo IdcupoNavigation { get; set; }
        public virtual Hestadoshabitacione IdestadoNavigation { get; set; }
    }
}