// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Hreservascierrediario
    {
        public int Idhotel { get; set; }
        public DateTime Fecha { get; set; }
        public int? Habocup { get; set; }
        public double? Porcocup { get; set; }
        public int? Gratis { get; set; }
        public int? Pax { get; set; }
        public double? Paxhab { get; set; }
        public double? Prodhrb { get; set; }
        public double? Dtos { get; set; }
        public double? Comis { get; set; }
        public double? Prodhrn { get; set; }
        public double? Preciohabb { get; set; }
        public double? Preciopaxb { get; set; }
        public double? Preciohabn { get; set; }
        public double? Preciopaxn { get; set; }
        public double? Extrasb { get; set; }
        public double? Extdtos { get; set; }
        public double? Extcomis { get; set; }
        public double? Extrasn { get; set; }
        public double? Prodn { get; set; }
        public double? Prodb { get; set; }
        public int? Habmes { get; set; }
        public double? Porcocupmes { get; set; }
        public int? Gratismes { get; set; }
        public int? Paxmes { get; set; }
        public double? Paxhabmes { get; set; }
        public double? Prodhrbmes { get; set; }
        public double? Dtosmes { get; set; }
        public double? Comismes { get; set; }
        public double? Prodhrnmes { get; set; }
        public double? Preciohabbmes { get; set; }
        public double? Preciopaxbmes { get; set; }
        public double? Preciohabnmes { get; set; }
        public double? Preciopaxnmes { get; set; }
        public double? Extrasbmes { get; set; }
        public double? Extdtosmes { get; set; }
        public double? Extcomismes { get; set; }
        public double? Extrasnmes { get; set; }
        public double? Prodnmes { get; set; }
        public double? Prodbmes { get; set; }
        public double? Habany { get; set; }
        public double? Porcocupany { get; set; }
        public int? Gratisany { get; set; }
        public int? Paxany { get; set; }
        public double? Paxhabany { get; set; }
        public double? Prodhrbany { get; set; }
        public double? Dtosany { get; set; }
        public double? Comisany { get; set; }
        public double? Prodhrnany { get; set; }
        public double? Preciohabbany { get; set; }
        public double? Preciopaxbany { get; set; }
        public double? Preciohabnany { get; set; }
        public double? Preciopaxnany { get; set; }
        public double? Extrasbany { get; set; }
        public double? Extdtosany { get; set; }
        public double? Extcomisany { get; set; }
        public double? Extrasnany { get; set; }
        public double? Prodnany { get; set; }
        public double? Prodbany { get; set; }
        public double? Saldoinicial { get; set; }
        public double? Acuenta { get; set; }
        public double? Cobros { get; set; }
        public double? Prodnpendfac { get; set; }
        public double? Saldofinal { get; set; }
        public int? Facturas { get; set; }
        public double? Descuadre { get; set; }
        public double? Base { get; set; }
        public double? Impuestos { get; set; }
        public double? Total { get; set; }
        public int? Habfut { get; set; }
        public double? Prodfut { get; set; }
        public double? Correcciones { get; set; }
        public double? Correccionesmes { get; set; }
        public double? Correccionesany { get; set; }
        public double? Prodncorr { get; set; }
        public double? Prodncorrmes { get; set; }
        public double? Prodncorrany { get; set; }
        public double? Cargosdtos { get; set; }
        public double? Cargosdtosmes { get; set; }
        public double? Cargosdtosany { get; set; }
    }
}