// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Hsuplemento
    {
        public int Id { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public int? Codarticulo { get; set; }
        public string Talla { get; set; }
        public string Color { get; set; }
        public short? Tiposuplemento { get; set; }
        public short? Tipocalculo { get; set; }
        public short? Aplicable { get; set; }
        public string Diasaplicable { get; set; }
        public short? Numdias { get; set; }
    }
}