// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Icgnombresetiqueta
    {
        public Icgnombresetiqueta()
        {
            Icgetiqueta = new HashSet<Icgetiqueta>();
        }

        public int Grupo { get; set; }
        public int Diseny { get; set; }
        public string Nombre { get; set; }
        public int? Codtitulo { get; set; }
        public byte[] Version { get; set; }

        public virtual ICollection<Icgetiqueta> Icgetiqueta { get; set; }
    }
}