// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class ItAvLog
    {
        public string Numserie { get; set; }
        public int Numalbaran { get; set; }
        public DateTime Fecha { get; set; }
        public int Reg { get; set; }
    }
}