// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Kitfase
    {
        public int Codarticulo { get; set; }
        public int Numfase { get; set; }
        public string Descripcion { get; set; }
        public int? Numerosserie { get; set; }
        public bool? Enbloque { get; set; }
        public byte[] Imagen { get; set; }
    }
}