// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class KpiFiltro
    {
        public KpiFiltro()
        {
            KpiFiltroDefs = new HashSet<KpiFiltroDef>();
        }

        public int Idfiltro { get; set; }
        public string Tablafiltro { get; set; }
        public string Camposid { get; set; }
        public string Campodesc { get; set; }

        public virtual ICollection<KpiFiltroDef> KpiFiltroDefs { get; set; }
    }
}