// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Mermaslin
    {
        public int Idint { get; set; }
        public int Numlin { get; set; }
        public int Codarticulo { get; set; }
        public string Talla { get; set; }
        public string Color { get; set; }
        public double? Unidades { get; set; }
        public double? ValoracionPvp { get; set; }
        public double? ValoracionCoste { get; set; }
        public double? Nuevostock { get; set; }

        public virtual Mermascab IdintNavigation { get; set; }
    }
}