// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Motivosabono
    {
        public Motivosabono()
        {
            MotivosabonoIdiomas = new HashSet<MotivosabonoIdioma>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public byte[] Version { get; set; }

        public virtual ICollection<MotivosabonoIdioma> MotivosabonoIdiomas { get; set; }
    }
}