// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Ordenesfabfase
    {
        public string Seriefab { get; set; }
        public int Numfab { get; set; }
        public int Numfase { get; set; }
        public string Numseriefabricado { get; set; }
        public DateTime? Fecha { get; set; }
        public DateTime? Hora { get; set; }
        public int? Codempleado { get; set; }
        public string Numseriecomponente { get; set; }
    }
}