// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Pedventacuponesgenerado
    {
        public string Numserie { get; set; }
        public int Numpedido { get; set; }
        public string N { get; set; }
        public int Idpromocion { get; set; }
        public string Eancupon { get; set; }
        public double? Unidades { get; set; }
        public double? Importedto { get; set; }
        public int? PromocionesclienteIdpromocion { get; set; }

        public virtual Pedventacab NNavigation { get; set; }
    }
}