// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Rangohora
    {
        public int Idperiodo { get; set; }
        public string Descripcion { get; set; }
        public DateTime? Horain { get; set; }
        public DateTime? Horafin { get; set; }
    }
}