// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Relcamposlibresubicacion
    {
        public int Tabla { get; set; }
        public int Subtipo { get; set; }
        public int Idgrupo { get; set; }
        public int Iddiseny { get; set; }

        public virtual Impresiondoc Id { get; set; }
    }
}