// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class RemDispositivoslin
    {
        public int Idfront { get; set; }
        public int Idterminal { get; set; }
        public string Tipodispositivo { get; set; }
        public string Nombre { get; set; }
        public int Posicion { get; set; }
        public string Secuencia { get; set; }

        public virtual RemDispositivo RemDispositivo { get; set; }
    }
}