// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class RemDisenysdoc
    {
        public int Idfront { get; set; }
        public short Tipo { get; set; }
        public int Grupo { get; set; }
        public int Codigo { get; set; }
        public int Nuevo { get; set; }
        public byte[] Version { get; set; }
        public int? Codalternativo { get; set; }
        public DateTime? Desdealternativo { get; set; }
        public DateTime? Hastaalternativo { get; set; }
    }
}