// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class RemIncidencia
    {
        public int Idincidencia { get; set; }
        public int Tipo { get; set; }
        public string Serie { get; set; }
        public int? Numero { get; set; }
        public DateTime? Fechadoc { get; set; }
        public int? Codproveedor { get; set; }
        public int? Idincidenciaorig { get; set; }
    }
}