// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Serviciosdocumento
    {
        public double Idintervencion { get; set; }
        public string Serie { get; set; }
        public int Numero { get; set; }
        public int Contador { get; set; }
        public string Ruta { get; set; }
        public int? Ordenfoto { get; set; }

        public virtual Servicio Servicio { get; set; }
    }
}