// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Tipoarreglo
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public double? Precio { get; set; }
        public int? Impuesto { get; set; }
        public double? Coste { get; set; }
        public string Cobrarporanticipado { get; set; }
    }
}