// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class TipospagoIdioma
    {
        public string Codtipopago { get; set; }
        public int Codidioma { get; set; }
        public int? Posicion { get; set; }
        public string Descripcion { get; set; }

        public virtual Tipospago CodtipopagoNavigation { get; set; }
    }
}