// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Tiposdium
    {
        public int Codtipodia { get; set; }
        public string Descripcion { get; set; }
        public int Colorfondo { get; set; }
        public int Colortexto { get; set; }
    }
}