// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Tiposreserva
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public bool? Cargos { get; set; }
        public bool Descatalogado { get; set; }
    }
}