// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Vendedoresplanincidencium
    {
        public int Codvendedor { get; set; }
        public string Codalmacen { get; set; }
        public DateTime Fecha { get; set; }
        public int Codtipo { get; set; }
        public DateTime Inicio { get; set; }
        public DateTime Fin { get; set; }
        public string Motivo { get; set; }
        public DateTime Dispinicio { get; set; }
        public DateTime Dispfin { get; set; }
        public double? Horas { get; set; }
        public bool? Aceptada { get; set; }
    }
}