// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Ventasacumulada
    {
        public int Anyo { get; set; }
        public int Mes { get; set; }
        public string Numserie { get; set; }
        public int Codcliente { get; set; }
        public int Codvendedor { get; set; }
        public string Codalmacen { get; set; }
        public int Codarticulo { get; set; }
        public string Talla { get; set; }
        public string Color { get; set; }
        public string N { get; set; }
        public double? Unidades { get; set; }
        public double? Unidadesalternativas { get; set; }
        public double? Importe { get; set; }
        public double? Importeiva { get; set; }
        public double? Coste { get; set; }
        public double? Costeiva { get; set; }
        public int Id { get; set; }
        public int? Anyomes { get; set; }
        public double? Udmedida2 { get; set; }
        public double? Importepromocion { get; set; }
        public double? Importepromocioniva { get; set; }
        public string Importado { get; set; }
        public int Codmoneda { get; set; }
        public double? Importedoc { get; set; }
        public double? Importeivadoc { get; set; }
        public double? Costedoc { get; set; }
        public double? Costeivadoc { get; set; }
    }
}