// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd2.Entities
{
    public partial class Ventascashdro
    {
        public string Serie { get; set; }
        public int Numero { get; set; }
        public string N { get; set; }
        public int Tipodoc { get; set; }
        public int Idtipodoc { get; set; }
        public bool Estado { get; set; }
        public DateTime? Fecha { get; set; }
        public bool Imprimir { get; set; }
        public int? Tipodocimp { get; set; }
        public int? Coddiseny { get; set; }
        public string Impresora { get; set; }
        public string Enlace { get; set; }
        public bool? Ticket { get; set; }
        public bool? Tarjeta { get; set; }
    }
}