// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Acumuladoretencione
    {
        public int Tipo { get; set; }
        public int Mes { get; set; }
        public int Anyo { get; set; }
        public int Codcliprov { get; set; }
        public int Codregimenartic { get; set; }
        public double? Pagado { get; set; }
        public double? Retenido { get; set; }
    }
}