// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Aeropuerto
    {
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Ciudad { get; set; }
        public string Codpais { get; set; }
        public string Descpais { get; set; }
        public string Schengen { get; set; }
        public string Unioneuropea { get; set; }
    }
}