// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Albventaregalo
    {
        public string Numserie { get; set; }
        public int Numalbaran { get; set; }
        public string N { get; set; }
        public int Idregalo { get; set; }
        public int Numlinea { get; set; }
        public double Unidades { get; set; }
        public double? Unidadesabonadas { get; set; }
        public int? Codvendedor { get; set; }

        public virtual Albventacab NNavigation { get; set; }
    }
}