// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Asignacionrecurso
    {
        public int Codgrupo { get; set; }
        public int Codrecurso { get; set; }

        public virtual Gruporecurso CodgrupoNavigation { get; set; }
        public virtual Recursosempresa CodrecursoNavigation { get; set; }
    }
}