// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Clientestarifascompra
    {
        public int Codcliente { get; set; }
        public int Codproveedor { get; set; }
        public int Idtarifac { get; set; }
        public bool? Compradirecta { get; set; }
        public byte[] Version { get; set; }

        public virtual Cliente CodclienteNavigation { get; set; }
        public virtual Tarifascompra Tarifascompra { get; set; }
    }
}