// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Clientesactividad
    {
        public int Codcliente { get; set; }
        public int Codactividad { get; set; }
        public int? Codcompetencia { get; set; }
        public double? Compras { get; set; }

        public virtual Actividade CodactividadNavigation { get; set; }
    }
}