// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Columnaslistadosorg
    {
        public int Idcol { get; set; }
        public string Tipo { get; set; }
        public string Descrip { get; set; }
        public string Visible { get; set; }
        public int? Ancho { get; set; }
        public int? Orden { get; set; }
    }
}