// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Comisionesvendedor
    {
        public int Codvendedor { get; set; }
        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }
        public int Codcomision { get; set; }

        public virtual Comisionescab CodcomisionNavigation { get; set; }
        public virtual Vendedore CodvendedorNavigation { get; set; }
    }
}