// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Complemento
    {
        public string Rfc { get; set; }
        public string Noidentificacion { get; set; }
        public int Codarticulo { get; set; }
        public string Descripcion { get; set; }
        public string Refproveedor { get; set; }
        public string Umedida { get; set; }
        public decimal Uds { get; set; }
    }
}