// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Configbotone
    {
        public int Tipo { get; set; }
        public int Codigo { get; set; }
        public string Clave { get; set; }
        public int Indice { get; set; }
        public string Caption { get; set; }
        public int? Valor { get; set; }
        public byte[] Version { get; set; }
    }
}