// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Docwordconfig
    {
        public int Tipodoc { get; set; }
        public string Path { get; set; }
        public string Plantilla { get; set; }

        public virtual Tiposdoc TipodocNavigation { get; set; }
    }
}