// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class EcuaTiposimpuestosespeciale
    {
        public int Cargodto { get; set; }
        public int? Tipo { get; set; }
        public string Valor { get; set; }
    }
}