// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Falta
    {
        public string Digitocontrol { get; set; }
        public int Tipo { get; set; }
        public string Numero { get; set; }
    }
}