// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Favoritosidioma
    {
        public int Codfavorito { get; set; }
        public int Codidioma { get; set; }
        public string Descripcion { get; set; }
        public byte[] Version { get; set; }
        public string Desclarga { get; set; }

        public virtual Favoritoscab CodfavoritoNavigation { get; set; }
        public virtual Idioma CodidiomaNavigation { get; set; }
    }
}