// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Foto
    {
        public Guid Idfoto { get; set; }
        public byte[] Foto1 { get; set; }
    }
}