// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Gruposarticulosusuario
    {
        public int Codusuario { get; set; }
        public int Id { get; set; }
        public int? Visibilidad { get; set; }
    }
}