// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class HioposEstadDimensione
    {
        public int Id { get; set; }
        public int Dimension { get; set; }
        public string Campolibre { get; set; }

        public virtual HioposEstad IdNavigation { get; set; }
    }
}