// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Historicocomisione
    {
        public int Codvendedor { get; set; }
        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }
        public int Codcomision { get; set; }
        public int Tipoarticulo { get; set; }
        public double? Porcentaje { get; set; }
        public double? Total { get; set; }
        public int? Codaux { get; set; }
        public int? Codmoneda { get; set; }
    }
}