// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Hotelescomentario
    {
        public int Idhotel { get; set; }
        public int Idcomentario { get; set; }
        public string Codidioma { get; set; }
        public string Comentario { get; set; }
        public byte[] Version { get; set; }
    }
}