// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Hreservasbloqueo
    {
        public int Idhotel { get; set; }
        public string Serie { get; set; }
        public int Idreserva { get; set; }
        public int Idlinea { get; set; }
        public string Terminal { get; set; }
        public DateTime Fechainibloqueo { get; set; }
        public DateTime Horainibloqueo { get; set; }

        public virtual Hreservascab Hreservascab { get; set; }
    }
}