// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Htiposvip
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int? Colorfondo { get; set; }
        public int? Colortexto { get; set; }
    }
}