// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Incidenciasnoautovalidable
    {
        public int Idincidencia { get; set; }
        public string Problemas { get; set; }

        public virtual Incidencia IdincidenciaNavigation { get; set; }
    }
}