// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Incidenciasconfig
    {
        public int Tipo { get; set; }
        public int Estado { get; set; }
        public int? Tipodocumento { get; set; }
        public string Codalmacen { get; set; }
    }
}