// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Interese
    {
        public Interese()
        {
            Clientesinteres = new HashSet<Clientesintere>();
        }

        public int Codinteres { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Clientesintere> Clientesinteres { get; set; }
    }
}