// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Lugaresreparacion
    {
        public int Codlugarreparacion { get; set; }
        public string Lugarreparacion { get; set; }
    }
}