// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Mappingsautomatizadosfile
    {
        public int Id { get; set; }
        public int Numfichero { get; set; }
        public string Fichero { get; set; }
        public string Ficherocopiadoa { get; set; }

        public virtual Mappingsautomatizado IdNavigation { get; set; }
    }
}