// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class NetConfigTipoTerminal
    {
        public int IdTipoTerminal { get; set; }
        public int IdParametro { get; set; }
        public string Valor { get; set; }

        public virtual NetTipoTerminal IdTipoTerminalNavigation { get; set; }
    }
}