// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class NetFamiliasNoModificable
    {
        public int IdFamilia { get; set; }
    }
}