// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class NetMotivosDevolucionTiendum
    {
        public int IdTienda { get; set; }
        public int IdMotivoDevolucion { get; set; }

        public virtual Motivosdevolucion IdMotivoDevolucionNavigation { get; set; }
        public virtual NetTiendum IdTiendaNavigation { get; set; }
    }
}