// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class NetPeticionReenvio
    {
        public Guid IdTerminal { get; set; }
        public int IdEntidad { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }

        public virtual NetTerminal IdTerminalNavigation { get; set; }
    }
}