// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Numerosserieregul
    {
        public int Codarticulo { get; set; }
        public string Talla { get; set; }
        public string Color { get; set; }
        public string Codalmacen { get; set; }
        public double? Unidades { get; set; }

        public virtual Articuloslin Articuloslin { get; set; }
    }
}