// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Parametro
    {
        public string Clave { get; set; }
        public string Subclave { get; set; }
        public string Usuario { get; set; }
        public string Valor { get; set; }
        public string Titulo { get; set; }
    }
}