// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Precioshoteldium
    {
        public int Codcliente { get; set; }
        public int Codtarifa { get; set; }
        public int Codhabitacion { get; set; }
        public DateTime Dia { get; set; }
        public double? Precio { get; set; }
        public byte[] Version { get; set; }
        public int Codregimen { get; set; }
        public int Idtemporada { get; set; }
        public double? Precioregimen { get; set; }

        public virtual Cliente CodclienteNavigation { get; set; }
        public virtual Articuloshabitacione CodhabitacionNavigation { get; set; }
        public virtual Articulosregimene CodregimenNavigation { get; set; }
        public virtual Tarifashotel CodtarifaNavigation { get; set; }
        public virtual Temporadashotel IdtemporadaNavigation { get; set; }
    }
}