// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Regimenfacturacion
    {
        public string Tiporegimen { get; set; }
        public string Codregimen { get; set; }
        public string Descripcion { get; set; }
    }
}