// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Reservasestado
    {
        public string Serie { get; set; }
        public int Idreserva { get; set; }
        public int Idlinea { get; set; }
        public int Tipo { get; set; }
        public string Codestado { get; set; }
        public int Dias { get; set; }

        public virtual Reserva Reserva { get; set; }
    }
}