// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Seriescamposlibre
    {
        public string Serie { get; set; }
        public int? Cliente { get; set; }
        public string Cuentacontable { get; set; }
        public string Almacen { get; set; }
        public string Seriefa { get; set; }
        public string Serienc { get; set; }
        public string Webpass { get; set; }

        public virtual Series SerieNavigation { get; set; }
    }
}