// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Serviciosparada
    {
        public string Serie { get; set; }
        public int Numero { get; set; }
        public double Idintervencion { get; set; }
        public int Codlinparada { get; set; }
        public int Codparada { get; set; }
        public string Horainicio { get; set; }
        public string Horafin { get; set; }
        public double? Tiempo { get; set; }

        public virtual Motivosparada CodparadaNavigation { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}