// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class ShowDiapositivaspresentacion
    {
        public int Idpresentacion { get; set; }
        public int Posicion { get; set; }
        public int? Iddiapositiva { get; set; }

        public virtual ShowDiapositiva IddiapositivaNavigation { get; set; }
        public virtual ShowPresentacione IdpresentacionNavigation { get; set; }
    }
}