// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Talla
    {
        public string Codtalla { get; set; }
        public int Posicion { get; set; }
        public string Talla1 { get; set; }
        public byte[] Version { get; set; }
    }
}