// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Tarifascompra
    {
        public Tarifascompra()
        {
            Almacenestarifas = new HashSet<Almacenestarifa>();
            Clientestarifascompras = new HashSet<Clientestarifascompra>();
            Condicionesproveedors = new HashSet<Condicionesproveedor>();
            Precioscompras = new HashSet<Precioscompra>();
        }

        public int Codproveedor { get; set; }
        public int Idtarifac { get; set; }
        public string Descripcion { get; set; }
        public DateTime? Fechaini { get; set; }
        public DateTime? Fechafin { get; set; }
        public string Coniva { get; set; }
        public int? Codmoneda { get; set; }
        public int? Posicion { get; set; }

        public virtual Proveedore CodproveedorNavigation { get; set; }
        public virtual ICollection<Almacenestarifa> Almacenestarifas { get; set; }
        public virtual ICollection<Clientestarifascompra> Clientestarifascompras { get; set; }
        public virtual ICollection<Condicionesproveedor> Condicionesproveedors { get; set; }
        public virtual ICollection<Precioscompra> Precioscompras { get; set; }
    }
}