// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Tarjetaspromocion
    {
        public int Idpromocion { get; set; }
        public int Idtipotarjeta { get; set; }

        public virtual Promocione IdpromocionNavigation { get; set; }
    }
}