// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Temporadaslin
    {
        public int Idtemporada { get; set; }
        public int Idlinea { get; set; }
        public DateTime? Fechainicio { get; set; }
        public DateTime? Fechafin { get; set; }
        public string Dias { get; set; }

        public virtual Temporadashotel IdtemporadaNavigation { get; set; }
    }
}