// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class TempInventario28206929230
    {
        public int Codarticulo { get; set; }
        public string Talla { get; set; }
        public string Color { get; set; }
        public string Id { get; set; }
        public string Descripcion { get; set; }
        public string Codbarras { get; set; }
        public string Codalmacen0 { get; set; }
        public DateTime? Fecharegul0 { get; set; }
        public double? Udsregul0 { get; set; }
        public double? Ventas0 { get; set; }
        public double? Compras0 { get; set; }
        public double? Entradas0 { get; set; }
        public double? Salidas0 { get; set; }
        public double? Consumidos0 { get; set; }
        public double? Fabricados0 { get; set; }
        public double? Transitos0 { get; set; }
        public double? Consumosinternos0 { get; set; }
        public double? Reparaciones0 { get; set; }
        public double? Stock0 { get; set; }
        public double? Valoracion0 { get; set; }
        public double? Udsregul20 { get; set; }
        public double? Ventas20 { get; set; }
        public double? Compras20 { get; set; }
        public double? Entradas20 { get; set; }
        public double? Salidas20 { get; set; }
        public double? Consumidos20 { get; set; }
        public double? Fabricados20 { get; set; }
        public double? Transitos20 { get; set; }
        public double? Consumosinternos20 { get; set; }
        public double? Stock20 { get; set; }
    }
}