// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.bd1.Entities
{
    public partial class Usuarioslistascodigo
    {
        public int Codusuario { get; set; }
        public int Tipolista { get; set; }
        public int Posicion { get; set; }
        public int? Codigo { get; set; }
    }
}